export const REACT_RELEASE = Object.freeze({
  product: "PENGUIN",
  version: "0.4.280",
  build: "2026.10.09.508",
  branch: "feature/react-firebase-port",
  commit: "MULTI-SURFACE-STORE-LOGO-COVER-BRANDING",
  dataService: "Firebase / Firestore",
  environment: "production",
  milestone: "Add per-store logo and cover uploads across all four ordering surfaces",
  whatsNew: [
    "Upload a store logo and branded hero background in store settings for Delivery, Table, Takeaway and Quick Order",
    "Use custom Edit/Delete SVG buttons on saved Delivery addresses",
    "Refine Delivery scooter hero emblem and restore soft-filled Edit/Delete address action icon buttons",
    "Update Delivery receipt payment review, Lalamove provider and inline item quantities",
    "Wrap Slip2Go verification note and long slip filenames within mobile delivery payment cards",
    "Make saved delivery address cards compact with single-row icon actions and selected-address caption",
    "Remove the redundant Home default-address button; use only nearby GPS matching and explicit saved-address selection",
    "Show a floating borderless Home favorite icon and wrap the saved delivery map description on mobile",
    "Fix compact address radio styling, rebalance modal icons and make mobile GPS map controls readable",
    "Show compact saved-address cards with one clickable home primary icon and an accessible full-size address editor",
    "Use an instant store-open switch beside the normal schedule action and show full weekday names",
    "Block public direct Firestore Delivery creates and enforce store hours in server transactions",
    "Set per-day Delivery hours and immediately close or reopen stores for emergencies",
    "Auto-select a saved address only within 100 metres of accurate GPS; otherwise request manual selection or save",
    "Share saved Delivery map pins with store-managed drivers using Google Maps",
    "Verify Restaurant Delivery PromptPay slips with central PENGUIN Slip2Go credits against each store's own PromptPay receiver",
    "Auto-release matched payments to Kitchen while routing unavailable or non-verifiable checks to trusted Cashier review",
    "Keep every Delivery visible to Cashier, admit COD immediately, and block unpaid prepayment orders from Kitchen",
  ],
});
