export const REACT_RELEASE = Object.freeze({
  product: "PENGUIN",
  version: "0.4.280",
  build: "2026.10.09.500",
  branch: "feature/react-firebase-port",
  commit: "DELIVERY-SAVED-ONLY-GPS-RADIUS",
  dataService: "Firebase / Firestore",
  environment: "production",
  milestone: "Never auto-select far saved addresses; require saved delivery destination and native Google pin",
  whatsNew: [
    "Use an instant store-open switch beside the normal schedule action and show full weekday names",
    "Block public direct Firestore Delivery creates and enforce store hours in server transactions",
    "Set per-day Delivery hours and immediately close or reopen stores for emergencies",
    "Auto-select a saved address only within 100 metres of accurate GPS; otherwise request manual selection or save",
    "Share saved Delivery map pins with store-managed drivers using Google Maps",
    "Verify Restaurant Delivery PromptPay slips with central PENGUIN Slip2Go credits against each store's own PromptPay receiver",
    "Auto-release matched payments to Kitchen while routing unavailable or non-verifiable checks to trusted Cashier review",
    "Keep every Delivery visible to Cashier, admit COD immediately, and block unpaid prepayment orders from Kitchen",
  ],
});
