import { useEffect, useRef, useState } from "react";
import { Navigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthProvider";
import { useTenant } from "@/tenant/TenantProvider";
import { useParityPage } from "@/hooks/useParityPage";
import { exportRetailPosBackup, restoreRetailPosBackup } from "@/data/retailPosSystemData";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";
import { PosNavigation } from "@/components/PosNavigation";
import { AppDeveloperPanel } from "@/components/AppDeveloperPanel";
import { useI18n } from "@/i18n/I18nProvider";

const INCLUDED=[["products","stats.products"],["categories","stats.categories"],["sales","stats.sales"],["returns","stats.returns"],["customers","stats.customers"],["loyaltyLedger","stats.loyalty"],["purchases","stats.purchases"],["suppliers","stats.suppliers"],["stockCounts","stats.stock_counts"],["stockMovements","stats.stock_movements"],["shifts","stats.shifts"],["taxInvoices","stats.tax_invoices"],["heldBills","stats.held_bills"],["settings","stats.settings"]];
export function PosBackupPage(){
 const authState=useAuth(),tenantState=useTenant(),{profile}=authState,{tenant}=tenantState,{t}=useI18n();
 const tr=(key,fallback)=>{const value=t("pos_backup."+key);return value&&value!=="pos_backup."+key?value:fallback};
 const stylesReady=useParityPage({title:tr("meta_title","สำรองและกู้คืนข้อมูล POS"),bodyClass:"pos-backup-page pos-backup-visual-page",disabledGlobalStyles:["app.css","icons.css","shared-responsive.css"],styles:["retail-pos-font-local.css","pos-locale-switcher-placement.css","retail-pos.css","retail-pos-backup.css","retail-pos-backup-visual-dashboard.css","retail-pos-navigation.css"]});
 const inputRef=useRef(null),[backup,setBackup]=useState(null),[fileName,setFileName]=useState(""),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(""),[error,setError]=useState(""),[stats,setStats]=useState(null),[dragging,setDragging]=useState(false);
 const countsOf=data=>Object.fromEntries(INCLUDED.map(([key])=>[key,Array.isArray(data.collections?.[key])?data.collections[key].length:0]));
 useEffect(()=>{if(!tenant?.id||!["owner","super_admin"].includes(profile?.role))return;let alive=true;exportRetailPosBackup().then(data=>{if(alive)setStats(countsOf(data))}).catch(error=>{console.warn("POS_BACKUP_SUMMARY_LOAD_FAILED",error);if(alive)setError(tr("messages.summary_failed","โหลดสรุปข้อมูลสำรองไม่สำเร็จ"))});return()=>{alive=false}},[tenant?.id,profile?.role]);
 const download=async()=>{setBusy("export");setError("");try{const data=await exportRetailPosBackup();setStats(countsOf(data));const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a"),url=URL.createObjectURL(blob);a.href=url;a.download="retail-pos-backup-"+String(data.exportedAt||new Date().toISOString()).replace(/[:T]/g,"-").slice(0,16)+".json";document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),500)}catch(e){console.error(e);setError(String(e?.message||tr("messages.export_failed","สร้างไฟล์สำรองไม่สำเร็จ")))}finally{setBusy("")}};
 const choose=async file=>{if(!file)return;setError("");try{const data=JSON.parse(await file.text());if(data.app!=="retail-pos-react"||Number(data.version)!==1)throw new Error(tr("messages.unsupported_file","ไฟล์สำรองนี้ไม่รองรับกับระบบ React/Firebase POS"));if(String(data.tenantId||"")!==String(tenant.id))throw new Error(tr("messages.wrong_store","ไฟล์สำรองเป็นข้อมูลของร้านอื่น ไม่สามารถกู้คืนในร้านนี้ได้"));setBackup(data);setFileName(file.name);setConfirmed(false);setStats(countsOf(data))}catch(e){setBackup(null);setFileName("");setError(String(e?.message||tr("messages.read_failed","อ่านไฟล์สำรองไม่สำเร็จ")))}};
 const clear=()=>{setBackup(null);setFileName("");setConfirmed(false);setStats(null);if(inputRef.current)inputRef.current.value=""};
 const restore=async()=>{if(!backup||!confirmed||busy)return;setBusy("restore");setError("");try{await restoreRetailPosBackup(backup);window.setTimeout(()=>location.replace("/pos"),700)}catch(e){console.error(e);setError(String(e?.message||tr("messages.restore_failed","กู้คืนข้อมูลไม่สำเร็จ")))}finally{setBusy("")}};
 if(authState.status==="loading"||tenantState.status==="loading"||!stylesReady)return null;if(!profile)return <Navigate to="/login?next=%2Fpos%2Fbackup" replace/>;if(!tenant)return <Navigate to="/" replace/>;if(!["owner","super_admin"].includes(profile.role))return <Navigate to="/pos" replace/>;
 return <><header className="pos-header" data-pos-supporting-header><div className="app-title"><div><strong>{tr("header.title","สำรองและกู้คืนข้อมูล")}</strong><small>{tr("header.subtitle","สำรองข้อมูล Retail POS ของร้านจาก Firebase และกู้คืนอย่างปลอดภัย")}</small></div></div><div className="header-actions"><LocaleSwitcher/><PosNavigation profile={profile} currentKey="pos.backup"/></div></header>
 <main className="backup-container" data-pos-supporting="backup"><section className="panel backup-panel backup-export-panel"><div className="backup-heading"><div><h1>{tr("export.title","สร้างไฟล์สำรอง")}</h1><p>{tr("export.description","ดาวน์โหลดข้อมูล Retail POS ของร้านจาก Firestore เป็นไฟล์ JSON")}</p></div><button id="exportBackupBtn" className="btn btn-pay" disabled={busy==="export"} onClick={download}>{busy==="export"?tr("export.progress","กำลังรวบรวมข้อมูลจาก Firebase..."):tr("export.action","ดาวน์โหลดไฟล์สำรอง")}</button></div>{stats?<div id="backupStats" className="backup-stats">{INCLUDED.map(([key,label])=><div key={key}><span>{tr(label,label)}</span><strong>{stats[key]||0}</strong></div>)}</div>:null}{busy==="export"?<div className="backup-progress"><span className="backup-spinner"/><span>{tr("export.progress","กำลังรวบรวมข้อมูลจาก Firebase...")}</span></div>:null}</section>
 <section className="panel backup-panel restore-panel backup-restore-panel"><div><h2>{tr("restore.title","กู้คืนจากไฟล์สำรอง")}</h2><p>{tr("restore.description","เลือกหรือลากไฟล์สำรอง JSON มาวาง ระบบจะตรวจสอบไฟล์ก่อนแทนที่ข้อมูล POS ของร้าน")}</p></div><label id="backupDropzone" className={"backup-dropzone"+(backup?" has-file":"")+(dragging?" is-dragover":"")} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={e=>{e.preventDefault();setDragging(false)}} onDrop={e=>{e.preventDefault();setDragging(false);choose([...e.dataTransfer.files].find(file=>file.name?.toLowerCase().endsWith(".json"))||e.dataTransfer.files?.[0])}}><input id="backupFile" ref={inputRef} type="file" accept="application/json,.json" onChange={e=>choose(e.target.files?.[0])}/><div className="backup-dropzone-content"><div className="backup-upload-icon">⇧</div><strong>{tr("restore.drop","ลากไฟล์สำรองมาวางที่นี่")}</strong><span>{tr("restore.choose","หรือคลิกเพื่อเลือกไฟล์ .json")}</span>{fileName?<small>{fileName}</small>:null}</div></label>{backup&&stats?<div id="restoreSummary" className="restore-summary">{INCLUDED.map(([key,label])=><div key={key}><span>{tr(label,label)}</span><strong>{stats[key]||0}</strong></div>)}</div>:null}{backup?<label className="confirm-row"><input id="replaceConfirm" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>{tr("restore.confirm","ฉันเข้าใจว่าการกู้คืนจะแทนที่ข้อมูล Retail POS ปัจจุบันของร้านนี้")}</span></label>:null}<p className="error-text">{error}</p><div className="restore-actions">{backup?<button id="clearSelectedBtn" className="btn btn-secondary" type="button" onClick={clear}>{tr("restore.clear","ล้างไฟล์ที่เลือก")}</button>:null}<button id="restoreBackupBtn" className="btn btn-pay" type="button" disabled={!backup||!confirmed||Boolean(busy)} onClick={restore}>{busy==="restore"?tr("restore.progress","กำลังกู้คืนข้อมูลใน Firebase..."):tr("restore.action","เริ่มกู้คืนข้อมูล")}</button></div>{busy==="restore"?<div className="backup-progress"><span className="backup-spinner"/><span>{tr("restore.progress","กำลังกู้คืนข้อมูลใน Firebase...")}</span></div>:null}</section>
 <section className="panel backup-note backup-included-panel"><h2>{tr("included.title","ข้อมูล Firestore ที่รวมในไฟล์สำรอง")}</h2><div className="included-grid">{INCLUDED.map(([key,label])=><span key={key}>{tr(label,label)}</span>)}</div><p>{tr("included.firebase_note","บัญชี Firebase Authentication และไฟล์รูปใน Storage จะไม่ถูกลบหรือสร้างใหม่จากการกู้คืนข้อมูล POS")}</p></section></main><AppDeveloperPanel/></>;
}
