import { useRef, useState } from "react";
import { Navigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthProvider";
import { useTenant } from "@/tenant/TenantProvider";
import { useParityPage } from "@/hooks/useParityPage";
import { exportRetailPosBackup, restoreRetailPosBackup } from "@/data/retailPosSystemData";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";
import { PosNavigation } from "@/components/PosNavigation";
import { AppDeveloperPanel } from "@/components/AppDeveloperPanel";

const INCLUDED=[["products","สินค้า"],["categories","หมวดสินค้า"],["sales","รายการขาย"],["returns","คืนสินค้า"],["customers","ลูกค้า"],["loyaltyLedger","แต้มสมาชิก"],["purchases","รับสินค้า/เจ้าหนี้"],["suppliers","ผู้จำหน่าย"],["stockCounts","ตรวจนับสต็อก"],["stockMovements","เคลื่อนไหวสต็อก"],["shifts","กะพนักงาน"],["taxInvoices","ใบกำกับภาษี"],["heldBills","บิลพัก"],["settings","การตั้งค่า"]];
export function PosBackupPage(){
 const authState=useAuth(),tenantState=useTenant(),{profile}=authState,{tenant}=tenantState;
 const stylesReady=useParityPage({title:"สำรองและกู้คืน",bodyClass:"pos-backup-page",disabledGlobalStyles:["app.css","icons.css","shared-responsive.css"],styles:["retail-pos-font-local.css","pos-locale-switcher-placement.css","retail-pos.css","retail-pos-backup.css","retail-pos-navigation.css"]});
 const inputRef=useRef(null),[backup,setBackup]=useState(null),[fileName,setFileName]=useState(""),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(""),[error,setError]=useState(""),[stats,setStats]=useState(null);
 const download=async()=>{setBusy("export");setError("");try{const data=await exportRetailPosBackup(),counts=Object.fromEntries(INCLUDED.map(([key])=>[key,Array.isArray(data.collections?.[key])?data.collections[key].length:0]));setStats(counts);const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="retail-pos-backup-"+String(data.exportedAt||new Date().toISOString()).slice(0,10)+".json";a.click();URL.revokeObjectURL(a.href)}catch(e){console.error(e);setError(String(e?.message||"สำรองข้อมูลไม่สำเร็จ"))}finally{setBusy("")}};
 const choose=async file=>{if(!file)return;setError("");try{const data=JSON.parse(await file.text());if(data.app!=="retail-pos-react"||Number(data.version)!==1)throw new Error("ไฟล์สำรองไม่รองรับ");if(String(data.tenantId||"")!==String(tenant.id))throw new Error("ไฟล์สำรองเป็นของร้านอื่น");setBackup(data);setFileName(file.name);setConfirmed(false);setStats(Object.fromEntries(INCLUDED.map(([key])=>[key,Array.isArray(data.collections?.[key])?data.collections[key].length:0])))}catch(e){setBackup(null);setFileName("");setError(String(e?.message||"อ่านไฟล์ไม่ได้"))}};
 const clear=()=>{setBackup(null);setFileName("");setConfirmed(false);setStats(null);if(inputRef.current)inputRef.current.value=""};
 const restore=async()=>{if(!backup||!confirmed||busy)return;setBusy("restore");setError("");try{await restoreRetailPosBackup(backup);window.setTimeout(()=>location.replace("/pos"),700)}catch(e){console.error(e);setError(String(e?.message||"กู้คืนไม่สำเร็จ"))}finally{setBusy("")}};
 if(authState.status==="loading"||tenantState.status==="loading"||!stylesReady)return null;if(!profile)return <Navigate to="/login?next=%2Freact%2Fpos%2Fbackup" replace/>;if(!tenant)return <Navigate to="/" replace/>;if(!["owner","super_admin"].includes(profile.role))return <Navigate to="/pos" replace/>;
 return <><header className="pos-header" data-pos-supporting-header><div className="app-title"><div><strong>สำรองและกู้คืน</strong><small>สำรองข้อมูล POS ของร้านและกู้คืนผ่าน Firebase Admin อย่างปลอดภัย</small></div></div><div className="header-actions"><LocaleSwitcher/><PosNavigation profile={profile} currentKey="pos.backup"/></div></header>
 <main className="backup-container" data-pos-supporting="backup"><section className="panel backup-panel"><div className="backup-heading"><div><h1>สำรองข้อมูล</h1><p>ดาวน์โหลดข้อมูล POS ของร้านเป็นไฟล์ JSON</p></div><button className="btn btn-pay" disabled={busy==="export"} onClick={download}>{busy==="export"?"กำลังสำรอง...":"ดาวน์โหลดไฟล์สำรอง"}</button></div>{stats?<div className="backup-stats">{INCLUDED.map(([key,label])=><div key={key}><span>{label}</span><strong>{stats[key]||0}</strong></div>)}</div>:null}{busy==="export"?<div className="backup-progress"><span className="backup-spinner"/><span>กำลังรวบรวมข้อมูลจาก Firebase</span></div>:null}</section>
 <section className="panel backup-panel restore-panel"><div><h2>กู้คืนข้อมูล</h2><p>การกู้คืนจะแทนที่ข้อมูล POS ของร้านนี้ด้วยข้อมูลจากไฟล์สำรอง</p></div><label className={"backup-dropzone"+(backup?" has-file":"")}><input ref={inputRef} type="file" accept="application/json,.json" onChange={e=>choose(e.target.files?.[0])}/><div className="backup-dropzone-content"><div className="backup-upload-icon">⇧</div><strong>ลากไฟล์ JSON มาวาง หรือเลือกไฟล์</strong><span>รองรับไฟล์สำรอง React/Firebase POS</span>{fileName?<small>{fileName}</small>:null}</div></label>{backup&&stats?<div className="restore-summary">{INCLUDED.map(([key,label])=><div key={key}><span>{label}</span><strong>{stats[key]||0}</strong></div>)}</div>:null}{backup?<label className="confirm-row"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>ยืนยันว่าให้แทนที่ข้อมูล POS ของร้านนี้</span></label>:null}<p className="error-text">{error}</p><div className="restore-actions">{backup?<button className="btn btn-secondary" onClick={clear}>ล้างไฟล์ที่เลือก</button>:null}<button className="btn btn-pay" disabled={!backup||!confirmed||Boolean(busy)} onClick={restore}>{busy==="restore"?"กำลังกู้คืน...":"กู้คืนข้อมูล"}</button></div>{busy==="restore"?<div className="backup-progress"><span className="backup-spinner"/><span>กำลังแทนที่ข้อมูลใน Firebase</span></div>:null}</section>
 <section className="panel backup-note"><h2>ข้อมูลที่รวมในไฟล์</h2><div className="included-grid">{INCLUDED.map(([,label])=><span key={label}>{label}</span>)}</div><p>บัญชี Firebase Authentication และไฟล์รูปใน Storage ไม่ถูกลบหรือสร้างใหม่จากการกู้คืนข้อมูล POS</p></section></main><AppDeveloperPanel/></>;
}
