import { useEffect, useMemo, useRef, useState } from "react";
import { Navigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthProvider";
import { useTenant } from "@/tenant/TenantProvider";
import { useI18n } from "@/i18n/I18nProvider";
import { useParityPage } from "@/hooks/useParityPage";
import { deletePosCustomer, listPosCustomers, listPosSales, savePosCustomer } from "@/data/retailPosData";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";
import { PosNavigation } from "@/components/PosNavigation";
import { AppDeveloperPanel } from "@/components/AppDeveloperPanel";
const empty={id:"",name:"",phone:"",email:"",address:"",note:"",active:true};
const asDate=v=>v?.toDate?.()||new Date(v||0);
export function PosCustomersPage(){
 const authState=useAuth(),tenantState=useTenant(),{profile}=authState,{tenant}=tenantState,{formatNumber}=useI18n(),formRef=useRef(null),historyRef=useRef(null);
 const stylesReady=useParityPage({title:"ทะเบียนลูกค้า",bodyClass:"pos-customers-page",disabledGlobalStyles:["app.css","icons.css","shared-responsive.css"],styles:["retail-pos-font-local.css","sweet-dialog.css","pos-locale-switcher-placement.css","retail-pos.css","retail-customers.css","retail-loyalty.css","retail-pos-navigation.css"]});
 const [customers,setCustomers]=useState([]),[sales,setSales]=useState([]),[ready,setReady]=useState(false),[search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[form,setForm]=useState(empty),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const money=v=>formatNumber(Number(v||0),{minimumFractionDigits:2,maximumFractionDigits:2});
 const refresh=async()=>{if(!tenant?.id)return;setReady(false);try{const [c,s]=await Promise.all([listPosCustomers(tenant.id),listPosSales(tenant.id)]);setCustomers(c);setSales(s)}finally{setReady(true)}};
 useEffect(()=>{refresh()},[tenant?.id]);
 const salesMap=useMemo(()=>{const map=new Map();sales.forEach(s=>{const key=String(s.customerId||"")||String(s.customerName||"").toLowerCase();if(!key)return;const row=map.get(key)||{count:0,total:0,last:null,rows:[]},gross=Number(s.totalAmount??s.total??0),net=Math.max(0,gross-Number(s.refundTotal||0)),date=s.createdAt;row.count++;row.total+=net;row.rows.push(s);if(!row.last||asDate(date)>asDate(row.last))row.last=date;map.set(key,row)});return map},[sales]);
 const summary=c=>salesMap.get(c.id)||salesMap.get(String(c.name||"").toLowerCase())||{count:0,total:0,last:null,rows:[]};
 const rows=useMemo(()=>customers.filter(c=>{const q=search.toLowerCase().trim(),match=!q||[c.customerCode,c.name,c.phone,c.email].join(" ").toLowerCase().includes(q);return match&&(filter==="all"||(filter==="active"?c.active!==false:c.active===false))}),[customers,search,filter]);
 const totals=useMemo(()=>customers.reduce((a,c)=>{const s=summary(c);a.sales+=s.total;a.bills+=s.count;return a},{sales:0,bills:0}),[customers,salesMap]);
 const openAdd=()=>{setForm(empty);setError("");formRef.current?.showModal?.()},openEdit=c=>{setForm({...empty,...c});setError("");formRef.current?.showModal?.()};
 const submit=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError("");try{await savePosCustomer(tenant.id,form,form.id);formRef.current?.close?.();await refresh()}catch(err){console.error(err);setError(String(err?.message||"บันทึกลูกค้าไม่สำเร็จ"))}finally{setBusy(false)}};
 const showHistory=c=>{setSelected(c);historyRef.current?.showModal?.()};
 const remove=async c=>{if(!confirm("ลบลูกค้า "+c.name+" ?"))return;try{await deletePosCustomer(tenant.id,c.id);await refresh()}catch(err){alert(String(err?.message||"ลบไม่สำเร็จ"))}};
 if(authState.status==="loading"||tenantState.status==="loading"||!stylesReady||(tenant?.id&&!ready))return null;if(!profile)return <Navigate to="/login?next=%2Fpos%2Fcustomers" replace/>;if(!tenant)return <Navigate to="/" replace/>;
 return <><header className="pos-header" data-pos-management-header><div className="app-title"><div><strong>ทะเบียนลูกค้า</strong><small>ข้อมูลสมาชิก ประวัติซื้อ และแต้มสะสม</small></div></div><div className="header-actions"><LocaleSwitcher/><PosNavigation profile={profile} currentKey="pos.customers"/></div></header>
 <main data-pos-management className="customer-container"><section className="customer-stats"><article><span>ลูกค้าทั้งหมด</span><strong>{customers.length}</strong></article><article><span>ใช้งาน</span><strong>{customers.filter(c=>c.active!==false).length}</strong></article><article><span>ยอดซื้อรวม</span><strong>{money(totals.sales)}</strong></article><article><span>จำนวนบิล</span><strong>{totals.bills}</strong></article></section><section className="panel customer-panel"><div className="section-heading customer-list-heading"><div><h2>รายชื่อลูกค้า</h2><p>จัดการข้อมูลและเปิดดูประวัติการซื้อ</p></div><button className="btn btn-pay" onClick={openAdd}>เพิ่มลูกค้า</button></div><div className="customer-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหารหัส ชื่อ เบอร์โทร หรืออีเมล"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">ทั้งหมด</option><option value="active">ใช้งาน</option><option value="inactive">ปิดใช้งาน</option></select></div><div className="customer-grid">{rows.map(c=>{const s=summary(c);return <article className="customer-card" key={c.id}><div className="customer-card-head"><div><strong>{c.name}</strong><span>{c.customerCode||"-"}</span></div><span className={"customer-status "+(c.active===false?"inactive":"active")}>{c.active===false?"ปิดใช้งาน":"ใช้งาน"}</span></div><p>{[c.phone,c.email].filter(Boolean).join(" • ")||"-"}</p><div className="customer-card-stats"><div><span>แต้ม</span><strong>{formatNumber(c.points||0)}</strong></div><div><span>ยอดซื้อ</span><strong>{money(s.total)}</strong></div><div><span>บิล</span><strong>{s.count}</strong></div></div><div className="customer-card-actions"><button className="btn btn-secondary" onClick={()=>showHistory(c)}>ประวัติ</button><button className="btn btn-secondary" onClick={()=>openEdit(c)}>แก้ไข</button>{["owner","admin"].includes(profile.role)?<button className="btn btn-danger" onClick={()=>remove(c)}>ลบ</button>:null}</div></article>})}</div>{!rows.length?<div className="empty-state">ไม่พบลูกค้า</div>:null}</section></main>
 <dialog ref={formRef} data-pos-management-dialog><form className="payment-form" onSubmit={submit}><div className="dialog-head"><h2>{form.id?"แก้ไขลูกค้า":"เพิ่มลูกค้า"}</h2><button type="button" className="icon-btn" onClick={()=>formRef.current?.close?.()}><i className="bi bi-x-lg"/></button></div><div className="customer-form-grid"><label className="full">ชื่อ<input required maxLength="120" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>โทรศัพท์<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>อีเมล<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="full">ที่อยู่<textarea rows="3" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label className="full">หมายเหตุ<textarea rows="2" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></div><p className="error-text">{error}</p><div className="dialog-actions"><button type="button" className="btn btn-secondary" onClick={()=>formRef.current?.close?.()}>ยกเลิก</button><button type="submit" className="btn btn-pay" disabled={busy}>บันทึก</button></div></form></dialog>
 <dialog ref={historyRef} data-pos-management-dialog><div className="customer-history-dialog"><div className="dialog-head"><h2>ประวัติการซื้อ — {selected?.name}</h2><button className="icon-btn" onClick={()=>historyRef.current?.close?.()}><i className="bi bi-x-lg"/></button></div><div className="customer-history-list">{selected?summary(selected).rows.sort((a,b)=>asDate(b.createdAt)-asDate(a.createdAt)).map(s=><article key={s.id}><div><strong>{s.saleNumber||s.id}</strong><span>{asDate(s.createdAt).toLocaleString("th-TH")}</span></div><strong>{money(Math.max(0,Number(s.totalAmount??s.total??0)-Number(s.refundTotal||0)))} บาท</strong></article>):null}</div></div></dialog><AppDeveloperPanel/></>;
}
