import { useEffect, useMemo, useRef, useState } from "react";
import { Navigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthProvider";
import { useTenant } from "@/tenant/TenantProvider";
import { useI18n } from "@/i18n/I18nProvider";
import { useParityPage } from "@/hooks/useParityPage";
import { listPosPurchases, recordPosPayablePayment } from "@/data/retailPurchasingData";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";
import { PosNavigation } from "@/components/PosNavigation";
import { AppDeveloperPanel } from "@/components/AppDeveloperPanel";
const today=()=>new Date().toISOString().slice(0,10);
export function PosPayablesPage(){
 const authState=useAuth(),tenantState=useTenant(),{profile}=authState,{tenant}=tenantState,{formatNumber}=useI18n(),dialogRef=useRef(null);
 const stylesReady=useParityPage({title:"เจ้าหนี้",bodyClass:"pos-payables-page",disabledGlobalStyles:["app.css","icons.css","shared-responsive.css"],styles:["retail-pos-font-local.css","pos-locale-switcher-placement.css","retail-pos.css","retail-payables.css","retail-pos-navigation.css"]});
 const [rows,setRows]=useState([]),[ready,setReady]=useState(false),[search,setSearch]=useState(""),[filter,setFilter]=useState("open"),[selected,setSelected]=useState(null),[date,setDate]=useState(today()),[amount,setAmount]=useState(""),[method,setMethod]=useState("cash"),[reference,setReference]=useState(""),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const money=v=>formatNumber(Number(v||0),{minimumFractionDigits:2,maximumFractionDigits:2}),now=today();
 const refresh=async()=>{if(!tenant?.id)return;setReady(false);try{setRows(await listPosPurchases(tenant.id))}finally{setReady(true)}};
 useEffect(()=>{refresh()},[tenant?.id]);
 const normalized=useMemo(()=>rows.map(p=>({...p,paidAmount:Number(p.paidAmount||0),balance:Number(p.balance??Math.max(0,Number(p.total||0)-Number(p.paidAmount||0))),paymentStatus:p.paymentStatus||((p.balance??p.total)>0?"unpaid":"paid")})),[rows]);
 const filtered=useMemo(()=>normalized.filter(p=>{const q=search.toLowerCase().trim(),match=!q||[p.supplierName,p.invoiceNo,p.id].join(" ").toLowerCase().includes(q);if(!match)return false;if(filter==="all")return true;if(filter==="open")return p.balance>0;if(filter==="overdue")return p.balance>0&&p.dueDate<now;return p.paymentStatus===filter}),[normalized,search,filter,now]);
 const stats=useMemo(()=>normalized.reduce((a,p)=>{if(p.balance>0){a.out+=p.balance;a.open++;if(p.dueDate<now)a.over+=p.balance;else{const days=Math.ceil((new Date(p.dueDate+"T00:00:00")-new Date(now+"T00:00:00"))/86400000);if(days<=7)a.soon+=p.balance}}return a},{out:0,open:0,soon:0,over:0}),[normalized,now]);
 const open=p=>{setSelected(p);setAmount(String(p.balance||""));setDate(today());setMethod("cash");setReference("");setNote("");setError("");dialogRef.current?.showModal?.()};
 const submit=async e=>{e.preventDefault();if(!selected||busy)return;setBusy(true);setError("");try{await recordPosPayablePayment(tenant.id,selected.id,{date,amount:Number(amount),method,reference,note});dialogRef.current?.close?.();await refresh()}catch(err){console.error(err);setError(String(err?.message||"บันทึกชำระไม่สำเร็จ"))}finally{setBusy(false)}};
 if(authState.status==="loading"||tenantState.status==="loading"||!stylesReady||(tenant?.id&&!ready))return null;if(!profile)return <Navigate to="/login?next=%2Freact%2Fpos%2Fpayables" replace/>;if(!tenant)return <Navigate to="/" replace/>;
 return <><header className="pos-header" data-pos-management-header><div className="app-title"><div><strong>เจ้าหนี้</strong><small>ติดตามยอดค้างชำระจากการรับสินค้า</small></div></div><div className="header-actions"><LocaleSwitcher/><PosNavigation profile={profile} currentKey="pos.payables"/></div></header><main data-pos-management className="payable-container">
 <section className="payable-stats"><article><span>ยอดค้างชำระ</span><strong>{money(stats.out)}</strong></article><article><span>รายการค้าง</span><strong>{stats.open}</strong></article><article><span>ครบกำหนดใน 7 วัน</span><strong>{money(stats.soon)}</strong></article><article><span>เกินกำหนด</span><strong>{money(stats.over)}</strong></article></section>
 <section className="panel payable-panel"><div className="section-heading"><div><h1>รายการเจ้าหนี้</h1><p>สรุปจากรายการรับสินค้าและประวัติการชำระ</p></div></div><div className="payable-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหาผู้จำหน่าย เลขที่เอกสาร หรือรายการ"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">ค้างชำระ</option><option value="unpaid">ยังไม่ชำระ</option><option value="partial">ชำระบางส่วน</option><option value="overdue">เกินกำหนด</option><option value="paid">ชำระแล้ว</option><option value="all">ทั้งหมด</option></select></div><div className="table-wrap"><table className="payable-table"><thead><tr><th>ผู้จำหน่าย</th><th>เอกสาร</th><th>วันที่รับ</th><th>ครบกำหนด</th><th className="number">ยอดรวม</th><th className="number">ชำระแล้ว</th><th className="number">คงเหลือ</th><th>สถานะ</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td>{p.supplierName}</td><td>{p.invoiceNo||p.id}</td><td>{p.purchaseDate}</td><td>{p.dueDate||"-"}</td><td className="number">{money(p.total)}</td><td className="number">{money(p.paidAmount)}</td><td className="number">{money(p.balance)}</td><td>{p.paymentStatus==="paid"?"ชำระแล้ว":p.paymentStatus==="partial"?"ชำระบางส่วน":"ยังไม่ชำระ"}</td><td>{p.balance>0?<button className="btn btn-pay" onClick={()=>open(p)}>ชำระ</button>:null}</td></tr>)}</tbody></table></div>{!filtered.length?<div className="empty-state">ไม่พบรายการเจ้าหนี้</div>:null}</section></main>
 <dialog ref={dialogRef} className="payment-dialog"><form method="dialog" onSubmit={submit}><h2>บันทึกชำระเจ้าหนี้</h2><p>{selected?.supplierName} • คงเหลือ {money(selected?.balance)}</p><div className="payment-grid"><label>วันที่<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>จำนวนเงิน<input type="number" min="0.01" step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>ช่องทาง<select value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">เงินสด</option><option value="transfer">โอนเงิน</option><option value="cheque">เช็ค</option><option value="other">อื่น ๆ</option></select></label><label>เลขอ้างอิง<input value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="payment-note">หมายเหตุ<input value={note} onChange={e=>setNote(e.target.value)}/></label></div><p className="error-text">{error}</p><div className="payment-actions"><button type="button" className="btn btn-secondary" onClick={()=>dialogRef.current?.close?.()}>ยกเลิก</button><button type="submit" className="btn btn-pay" disabled={busy}>บันทึก</button></div><button className="close-dialog" type="button" onClick={()=>dialogRef.current?.close?.()}>×</button></form></dialog><AppDeveloperPanel/></>;
}
