import { useEffect, useMemo, useState } from "react";
import { Navigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthProvider";
import { useTenant } from "@/tenant/TenantProvider";
import { useI18n } from "@/i18n/I18nProvider";
import { useParityPage } from "@/hooks/useParityPage";
import { listRetailProducts } from "@/data/retailProductsData";
import { listPosPurchases, listPosSuppliers, receivePosPurchase } from "@/data/retailPurchasingData";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";
import { PosNavigation } from "@/components/PosNavigation";
import { AppDeveloperPanel } from "@/components/AppDeveloperPanel";
const today=()=>new Date().toISOString().slice(0,10);
export function PosPurchasesPage(){
 const authState=useAuth(),tenantState=useTenant(),{profile}=authState,{tenant}=tenantState,{formatNumber}=useI18n();
 const stylesReady=useParityPage({title:"รับสินค้าเข้า",bodyClass:"pos-purchases-page",disabledGlobalStyles:["app.css","icons.css","shared-responsive.css"],styles:["retail-pos-font-local.css","pos-locale-switcher-placement.css","retail-pos.css","retail-purchases.css","retail-purchases-report.css","retail-pos-navigation.css"]});
 const [products,setProducts]=useState([]),[suppliers,setSuppliers]=useState([]),[history,setHistory]=useState([]),[ready,setReady]=useState(false),[supplierName,setSupplierName]=useState(""),[invoiceNo,setInvoiceNo]=useState(""),[purchaseDate,setPurchaseDate]=useState(today()),[note,setNote]=useState(""),[lines,setLines]=useState([{id:crypto.randomUUID(),productId:"",qty:1,unitCost:""}]),[search,setSearch]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const money=v=>formatNumber(Number(v||0),{minimumFractionDigits:2,maximumFractionDigits:2});
 const refresh=async()=>{if(!tenant?.id)return;setReady(false);try{const [p,s,h]=await Promise.all([listRetailProducts(tenant.id),listPosSuppliers(tenant.id),listPosPurchases(tenant.id)]);setProducts(p);setSuppliers(s);setHistory(h)}finally{setReady(true)}};
 useEffect(()=>{refresh()},[tenant?.id]);
 const supplier=suppliers.find(s=>String(s.name).toLowerCase()===supplierName.trim().toLowerCase());
 const total=lines.reduce((a,l)=>a+Number(l.qty||0)*Number(l.unitCost||0),0);
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return history.filter(p=>!q||[p.id,p.supplierName,p.invoiceNo,(p.items||[]).map(i=>i.productName).join(" ")].join(" ").toLowerCase().includes(q))},[history,search]);
 const update=(id,key,value)=>setLines(lines.map(l=>l.id===id?{...l,[key]:value}:l));
 const add=()=>setLines([...lines,{id:crypto.randomUUID(),productId:"",qty:1,unitCost:""}]),remove=id=>setLines(lines.length>1?lines.filter(l=>l.id!==id):lines);
 const reset=()=>{setSupplierName("");setInvoiceNo("");setPurchaseDate(today());setNote("");setLines([{id:crypto.randomUUID(),productId:"",qty:1,unitCost:""}]);setError("")};
 const submit=async e=>{e.preventDefault();if(busy)return;const items=lines.map(l=>{const p=products.find(x=>x.id===l.productId);return{productId:l.productId,productName:p?.name||"",qty:Number(l.qty||0),unitCost:Number(l.unitCost||0)}});setBusy(true);setError("");try{await receivePosPurchase({tenantId:tenant.id,supplierName,supplierId:supplier?.id||"",invoiceNo,purchaseDate,note,items});reset();await refresh()}catch(err){console.error(err);setError(String(err?.message||"บันทึกรับสินค้าไม่สำเร็จ"))}finally{setBusy(false)}};
 if(authState.status==="loading"||tenantState.status==="loading"||!stylesReady||(tenant?.id&&!ready))return null;if(!profile)return <Navigate to="/login?next=%2Fpos%2Fpurchases" replace/>;if(!tenant)return <Navigate to="/" replace/>;
 return <><header className="pos-header" data-pos-management-header><div className="app-title"><div><strong>รับสินค้าเข้า</strong><small>บันทึกรับสินค้า ปรับต้นทุนเฉลี่ย และเพิ่มสต็อก</small></div></div><div className="header-actions"><LocaleSwitcher/><PosNavigation profile={profile} currentKey="pos.purchases"/></div></header>
 <main data-pos-management className="purchase-container"><section className="panel purchase-form-panel"><div className="section-heading"><div><h1>รับสินค้าเข้า</h1><p>ยอดสต็อกและต้นทุนเฉลี่ยจะอัปเดตทันทีหลังบันทึก</p></div></div><form onSubmit={submit}><div className="purchase-meta-grid"><label>ผู้จำหน่าย<input required list="supplierList" value={supplierName} onChange={e=>setSupplierName(e.target.value)} placeholder="เลือกหรือพิมพ์ชื่อผู้จำหน่าย"/><datalist id="supplierList">{suppliers.map(s=><option key={s.id} value={s.name}>{s.contact||s.phone||""}</option>)}</datalist><small>{supplier?[supplier.contact,supplier.phone,Number(supplier.creditDays)>0?"เครดิต "+supplier.creditDays+" วัน":""].filter(Boolean).join(" • "):"เลือกจากทะเบียนผู้จำหน่าย"}</small></label><label>เลขที่ใบส่งของ / ใบกำกับ<input value={invoiceNo} onChange={e=>setInvoiceNo(e.target.value)} maxLength="80"/></label><label>วันที่รับสินค้า<input type="date" required value={purchaseDate} onChange={e=>setPurchaseDate(e.target.value)}/></label><label>หมายเหตุ<input value={note} onChange={e=>setNote(e.target.value)} maxLength="200"/></label></div>
 <div className="purchase-lines-heading"><h2>สินค้า</h2><button type="button" className="btn btn-secondary" onClick={add}><i className="bi bi-plus-lg"/><span>เพิ่มสินค้า</span></button></div><div className="purchase-table-wrap"><table className="purchase-table"><thead><tr><th>สินค้า</th><th className="number">สต็อกก่อน</th><th className="number">จำนวนรับ</th><th className="number">ต้นทุนต่อหน่วย</th><th className="number">รวม</th><th></th></tr></thead><tbody>{lines.map(l=>{const p=products.find(x=>x.id===l.productId);return <tr key={l.id}><td><select value={l.productId} onChange={e=>update(l.id,"productId",e.target.value)}><option value="">-- เลือกสินค้า --</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} ({p.id})</option>)}</select></td><td className="number">{formatNumber(p?.stock||0)}</td><td><input type="number" min="0.001" step="0.001" value={l.qty} onChange={e=>update(l.id,"qty",e.target.value)}/></td><td><input type="number" min="0" step="0.01" value={l.unitCost} onChange={e=>update(l.id,"unitCost",e.target.value)}/></td><td className="number">{money(Number(l.qty||0)*Number(l.unitCost||0))}</td><td><button type="button" className="remove-line" onClick={()=>remove(l.id)}><i className="bi bi-trash3"/></button></td></tr>})}</tbody></table></div><div className="purchase-summary"><span>ยอดรวม</span><strong>{money(total)} บาท</strong></div><p className="error-text">{error}</p><div className="purchase-actions"><button type="button" className="btn btn-secondary" onClick={reset}><i className="bi bi-x-lg"/><span>ล้าง</span></button><button type="submit" className="btn btn-pay" disabled={busy}><i className="bi bi-floppy"/><span>บันทึก</span></button></div></form></section>
 <section className="panel purchase-history-panel"><div className="section-heading"><div><h2>ประวัติรับสินค้า</h2><p>รายการรับสินค้าล่าสุด</p></div></div><label className="purchase-history-search">ค้นหา<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหาเลขที่รายการ ผู้จำหน่าย หรือสินค้า"/></label><div className="purchase-history">{filtered.map(p=><article className="purchase-history-item" key={p.id}><div className="purchase-history-head"><div><strong>{p.supplierName}</strong><span>{p.id}{p.invoiceNo?" • "+p.invoiceNo:""}</span></div><div className="purchase-history-total"><strong>{money(p.total)} บาท</strong><span>{p.purchaseDate}</span></div></div><div className="purchase-history-meta">{p.note||"ไม่มีหมายเหตุ"}</div><div className="purchase-history-lines">{(p.items||[]).map(i=><div className="purchase-history-line" key={i.productId}><span>{i.productName} × {formatNumber(i.qty)}</span><strong>{money(i.lineTotal)}</strong></div>)}</div></article>)}</div>{!filtered.length?<div className="empty-state">ยังไม่มีประวัติรับสินค้า</div>:null}</section></main><AppDeveloperPanel/></>;
}
