import { useEffect, useMemo, useState } from "react";
import { Navigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthProvider";
import { useTenant } from "@/tenant/TenantProvider";
import { useI18n } from "@/i18n/I18nProvider";
import { useParityPage } from "@/hooks/useParityPage";
import { createPosReturn, listPosReturns, listPosSales } from "@/data/retailPosData";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";
import { PosNavigation } from "@/components/PosNavigation";
import { AppDeveloperPanel } from "@/components/AppDeveloperPanel";
const asDate=v=>v?.toDate?.()||new Date(v||0);
const returnedMap=s=>(s?.returns||[]).reduce((m,r)=>{(r.items||[]).forEach(i=>m[i.productId]=Number(m[i.productId]||0)+Number(i.qty||0));return m},{});
export function PosReturnsPage(){
 const authState=useAuth(),tenantState=useTenant(),{profile}=authState,{tenant}=tenantState,{formatNumber}=useI18n();
 const stylesReady=useParityPage({title:"คืนสินค้า",bodyClass:"pos-returns-page",disabledGlobalStyles:["app.css","icons.css","shared-responsive.css"],styles:["retail-pos-font-local.css","pos-locale-switcher-placement.css","retail-pos.css","retail-returns.css","retail-returns-mobile.css","retail-return-receipt.css","retail-pos-navigation.css"]});
 const [sales,setSales]=useState([]),[history,setHistory]=useState([]),[ready,setReady]=useState(false),[mode,setMode]=useState("receipt"),[query,setQuery]=useState(""),[selected,setSelected]=useState(null),[qtys,setQtys]=useState({}),[reason,setReason]=useState(""),[note,setNote]=useState(""),[refundMethod,setRefundMethod]=useState("original"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[historySearch,setHistorySearch]=useState("");
 const money=v=>formatNumber(Number(v||0),{minimumFractionDigits:2,maximumFractionDigits:2});
 const refresh=async()=>{if(!tenant?.id)return;setReady(false);try{const [s,h]=await Promise.all([listPosSales(tenant.id),listPosReturns(tenant.id)]);setSales(s);setHistory(h)}finally{setReady(true)}};
 useEffect(()=>{refresh()},[tenant?.id]);
 const results=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return[];return sales.filter(s=>{if(mode==="receipt")return String(s.saleNumber||s.id).toLowerCase().includes(q);const items=s.items||[];if(mode==="barcode")return items.some(i=>String(i.barcode||"").toLowerCase().includes(q));return items.some(i=>String(i.name||i.productName||"").toLowerCase().includes(q))}).slice(0,20)},[sales,query,mode]);
 const returned=useMemo(()=>returnedMap(selected),[selected]);
 const rows=useMemo(()=>(selected?.items||[]).map(i=>{const id=String(i.productId||i.id||""),sold=Number(i.qty||0),was=Number(returned[id]||0),remain=Math.max(0,sold-was),qty=Math.min(remain,Math.max(0,Number(qtys[id]||0)));return{...i,id,sold,was,remain,qty,refund:qty*Number(i.price||0)}}),[selected,returned,qtys]);
 const total=rows.reduce((a,r)=>a+r.refund,0);
 const choose=s=>{setSelected(s);setQtys({});setReason("");setNote("");setError("")};
 const clear=()=>{setSelected(null);setQtys({});setError("")};
 const submit=async(voidAll=false)=>{if(!selected||busy)return;const items=rows.filter(r=>voidAll?r.remain>0:r.qty>0).map(r=>({productId:r.id,qty:voidAll?r.remain:r.qty}));if(!items.length){setError("กรุณาระบุจำนวนสินค้าที่ต้องการคืน");return}if(!reason.trim()){setError("กรุณาระบุเหตุผลการคืนสินค้า");return}setBusy(true);setError("");try{await createPosReturn({tenantId:tenant.id,saleId:selected.id,items,mode:voidAll?"void":"return",reason,refundMethod,note});await refresh();clear()}catch(e){console.error(e);setError(String(e?.message||"คืนสินค้าไม่สำเร็จ"))}finally{setBusy(false)}};
 const filteredHistory=useMemo(()=>{const q=historySearch.toLowerCase().trim();return history.filter(r=>!q||[r.returnNumber,r.saleNumber,r.reason].join(" ").toLowerCase().includes(q))},[history,historySearch]);
 if(authState.status==="loading"||tenantState.status==="loading"||!stylesReady||(tenant?.id&&!ready))return null;if(!profile)return <Navigate to="/login?next=%2Fpos%2Freturns" replace/>;if(!tenant)return <Navigate to="/" replace/>;
 return <><header className="pos-header" data-pos-management-header><div className="app-title"><div><strong>คืนสินค้า</strong><small>ค้นหาบิลและคืนสินค้าเข้าสต็อก</small></div></div><div className="header-actions"><LocaleSwitcher/><PosNavigation profile={profile} currentKey="pos.returns"/></div></header>
 <main data-pos-management className="return-container"><section className="panel return-search-panel"><div className="section-heading"><div><h2>ค้นหารายการขาย</h2><p>ค้นหาจากเลขที่บิล ชื่อสินค้า หรือบาร์โค้ด</p></div></div><div className="return-search-mode-row"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="receipt">เลขที่บิล</option><option value="product">ชื่อสินค้า</option><option value="barcode">บาร์โค้ด</option></select></div><div className="return-search-row"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={mode==="receipt"?"ค้นหาเลขที่บิล":mode==="barcode"?"สแกนหรือพิมพ์บาร์โค้ด":"ค้นหาชื่อสินค้า"}/><button className="btn btn-pay" type="button"><i className="bi bi-search"/><span>ค้นหา</span></button></div><div className="return-sale-results">{results.map(s=><button className="return-sale-result" key={s.id} onClick={()=>choose(s)}><strong>{s.saleNumber||s.id}</strong><span>{asDate(s.createdAt).toLocaleString("th-TH")} • {money(s.totalAmount||s.total)} บาท</span></button>)}</div>{query&&!results.length?<div className="empty-state">ไม่พบบิลที่ค้นหา</div>:!query?<div className="empty-state">กรอกคำค้นหาเพื่อเริ่มต้น</div>:null}</section>
 {selected?<section className="panel return-editor-panel"><div className="return-editor-head section-heading"><div><h1>{selected.saleNumber||selected.id}</h1><p>{asDate(selected.createdAt).toLocaleString("th-TH")} • ยอดเดิม {money(selected.totalAmount||selected.total)} บาท</p></div><button className="btn btn-secondary" onClick={clear}>เลือกบิลใหม่</button></div><div className="table-wrap"><table className="return-table"><thead><tr><th>สินค้า</th><th className="number">ขายแล้ว</th><th className="number">คืนแล้ว</th><th className="number">คืนครั้งนี้</th><th className="number">ราคาต่อหน่วย</th><th className="number">ยอดคืน</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name||r.productName}</td><td className="number">{formatNumber(r.sold)}</td><td className="number">{formatNumber(r.was)}</td><td className="number"><input type="number" min="0" max={r.remain} step="1" disabled={!r.remain} value={qtys[r.id]??""} onChange={e=>setQtys({...qtys,[r.id]:e.target.value})}/></td><td className="number">{money(r.price)}</td><td className="number">{money(r.refund)}</td></tr>)}</tbody></table></div><div className="return-form-grid"><label>วันที่คืนสินค้า<input type="date" value={new Date().toISOString().slice(0,10)} readOnly/></label><label>ช่องทางคืนเงิน<select value={refundMethod} onChange={e=>setRefundMethod(e.target.value)}><option value="cash">เงินสด</option><option value="transfer">โอนเงิน</option><option value="original">ช่องทางเดิม</option><option value="credit">เครดิตร้าน</option></select></label><label className="full">เหตุผลการคืน<input maxLength="200" required value={reason} onChange={e=>setReason(e.target.value)} placeholder="เช่น สินค้าชำรุด / ลูกค้าซื้อผิด"/></label><label className="full">หมายเหตุ<input maxLength="300" value={note} onChange={e=>setNote(e.target.value)}/></label></div><div className="return-summary"><span>ยอดคืนรวม</span><strong>{money(total)} บาท</strong></div><p className="error-text">{error}</p><div className="return-actions"><button className="btn btn-secondary" disabled={busy} onClick={()=>submit(true)}>คืนทั้งบิล / VOID</button><button className="btn btn-pay" disabled={busy||total<=0} onClick={()=>submit(false)}>ยืนยันคืนสินค้าและคืนเงิน</button></div></section>:null}
 <section className="panel return-history-panel"><div className="section-heading"><div><h2>ประวัติการคืนสินค้า</h2><p>รายการคืนล่าสุดจากฐานข้อมูล</p></div></div><label className="return-history-search">ค้นหารายการ<input value={historySearch} onChange={e=>setHistorySearch(e.target.value)} placeholder="ค้นหาเลขที่คืน บิลเดิม หรือเหตุผล"/></label><div className="return-history">{filteredHistory.map(r=><article className="return-history-row" key={r.id}><div><strong>{r.returnNumber||r.id}</strong><span>{r.saleNumber||r.saleId} • {asDate(r.createdAt).toLocaleString("th-TH")}</span><small>{r.reason||"-"}</small></div><div><strong>{money(r.refundTotal)} บาท</strong><span>{r.mode==="void"?"VOID":"คืนสินค้า"}</span></div></article>)}</div>{!filteredHistory.length?<div className="empty-state">ยังไม่มีประวัติการคืนสินค้า</div>:null}</section></main><AppDeveloperPanel/></>;
}
