import { useEffect, useState } from "react";
import { Navigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthProvider";
import { useTenant } from "@/tenant/TenantProvider";
import { useI18n } from "@/i18n/I18nProvider";
import { useParityPage } from "@/hooks/useParityPage";
import { loadPosStoreSettings, savePosStoreSettings } from "@/data/retailPosData";
import { AdminMap } from "@/pages/AdminPage";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";
import { PosNavigation } from "@/components/PosNavigation";
import { AppDeveloperPanel } from "@/components/AppDeveloperPanel";
import { POS_THEME_OPTIONS, DEFAULT_POS_THEME, applyPosTheme, normalizePosTheme } from "@/config/posThemes";
const defaults={shopName:"",shopAddress:"",shopPhone:"",taxId:"",storeLatitude:"",storeLongitude:"",vatRegistered:"no",vatRate:7,defaultVatMode:"include",taxBranchType:"headOffice",taxBranchCode:"",taxInvoiceName:"",taxInvoiceAddress:"",promptPayEnabled:"no",promptPayId:"",promptPayAccountName:"",receiptPaperSize:"80",receiptPrintMode:"none",receiptThanks:"ขอบคุณที่ใช้บริการ",receiptFooter:"",loyaltyEnabled:"yes",spendPerPoint:10,pointValue:1,posTheme:DEFAULT_POS_THEME};
export function PosSettingsPage(){
 const authState=useAuth(),tenantState=useTenant(),{profile}=authState,{tenant}=tenantState,{t}=useI18n();
 const stylesReady=useParityPage({title:"ตั้งค่าร้านค้าปลีก",bodyClass:"pos-settings-page",disabledGlobalStyles:["app.css","icons.css","shared-responsive.css"],styles:["retail-pos-font-local.css","pos-locale-switcher-placement.css","retail-pos.css","retail-pos-settings.css","retail-loyalty.css","retail-pos-navigation.css"]});
 const [form,setForm]=useState(defaults),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[mapError,setMapError]=useState("");
 const load=async()=>{if(!tenant?.id)return;setReady(false);try{const s=await loadPosStoreSettings(tenant.id),store=s.store||{},tax=s.tax||{},payment=s.payment||{},receipt=s.receipt||{},loyalty=s.loyalty||{},theme=s.posTheme||{};const posTheme=normalizePosTheme(theme.theme||DEFAULT_POS_THEME);setForm({...defaults,...store,...tax,...payment,...receipt,vatRegistered:tax.vatRegistered===true?"yes":"no",promptPayEnabled:payment.promptPayEnabled===true?"yes":"no",loyaltyEnabled:loyalty.enabled===false?"no":"yes",storeLatitude:store.storeLatitude??"",storeLongitude:store.storeLongitude??"",posTheme});applyPosTheme(posTheme,tenant.id)}finally{setReady(true)}};
 useEffect(()=>{load()},[tenant?.id]);
 const change=(key,value)=>{if(key==="posTheme")applyPosTheme(value,tenant?.id,{cache:false});setForm(f=>({...f,[key]:value}))};
 const location=form.storeLatitude!==""&&form.storeLongitude!==""?{latitude:Number(form.storeLatitude),longitude:Number(form.storeLongitude)}:null;
 const setLocation=loc=>{if(!loc)return;setForm(f=>({...f,storeLatitude:loc.latitude,storeLongitude:loc.longitude}))};
 const currentLocation=()=>navigator.geolocation?.getCurrentPosition(pos=>setLocation({latitude:Number(pos.coords.latitude.toFixed(7)),longitude:Number(pos.coords.longitude.toFixed(7))}),()=>setMapError("ไม่สามารถอ่านตำแหน่งปัจจุบันได้"),{enableHighAccuracy:true,timeout:10000});
 const submit=async e=>{e.preventDefault();setBusy(true);setError("");try{const saved=await savePosStoreSettings(tenant.id,form);const posTheme=normalizePosTheme(saved.posTheme?.theme||form.posTheme);applyPosTheme(posTheme,tenant.id);setForm(f=>({...f,posTheme}))}catch(err){console.error(err);setError(String(err?.message||"บันทึกการตั้งค่าไม่สำเร็จ"))}finally{setBusy(false)}};
 if(authState.status==="loading"||tenantState.status==="loading"||!stylesReady||(tenant?.id&&!ready))return null;if(!profile)return <Navigate to="/login?next=%2Fpos%2Fsettings" replace/>;if(!tenant)return <Navigate to="/" replace/>;
 return <><header className="pos-header" data-pos-supporting-header><div className="app-title"><div><strong>ตั้งค่าร้านค้าปลีก</strong><small>ข้อมูลร้าน รูปแบบใบเสร็จ ภาษี และระบบสมาชิก</small></div></div><div className="header-actions"><LocaleSwitcher/><PosNavigation profile={profile} currentKey="pos.settings"/></div></header><main className="settings-container" data-pos-supporting="settings"><form className="panel settings-panel" onSubmit={submit}>
 <section><div className="section-heading"><div><h1>ข้อมูลร้าน</h1><p>ข้อมูลนี้จะแสดงบนใบเสร็จรับเงิน</p></div></div><div className="settings-grid"><label className="full">ชื่อร้าน<input required value={form.shopName} onChange={e=>change("shopName",e.target.value)}/></label><label className="full">ที่อยู่ร้าน<textarea rows="3" value={form.shopAddress} onChange={e=>change("shopAddress",e.target.value)}/></label><label>เบอร์โทรศัพท์<input value={form.shopPhone} onChange={e=>change("shopPhone",e.target.value)}/></label><label>เลขประจำตัวผู้เสียภาษี<input value={form.taxId} onChange={e=>change("taxId",e.target.value)}/></label></div><div className="store-location-picker"><div className="store-location-head"><div><strong>ตำแหน่งร้าน</strong><p>เลือกตำแหน่งร้านบนแผนที่ หรือลากหมุด</p></div><button type="button" className="btn btn-secondary" onClick={currentLocation}>ใช้ตำแหน่งปัจจุบัน</button></div><AdminMap tenantSlug={tenant.slug||profile.tenantSlug||""} location={location} onLocation={setLocation} onError={setMapError} t={t}/><div className="store-location-footer"><span>{location?"กำหนดตำแหน่งแล้ว":"ยังไม่ได้กำหนดตำแหน่งร้าน"}</span><span>{location?location.latitude+", "+location.longitude:""}</span></div>{mapError?<p className="settings-note">{mapError}</p>:null}</div></section>
 <section className="pos-theme-settings-section"><div className="section-heading"><div><h2>{t("pos_settings.theme.title")}</h2><p>{t("pos_settings.theme.description")}</p></div></div><div className="pos-theme-picker" role="radiogroup" aria-label={t("pos_settings.theme.title")}>
  {POS_THEME_OPTIONS.map(option=><label className="pos-theme-choice" data-theme-preview={option.id} key={option.id}><input type="radio" name="posTheme" value={option.id} checked={form.posTheme===option.id} onChange={e=>change("posTheme",e.target.value)}/><div><div className="pos-theme-choice-head"><span className="pos-theme-choice-number">{option.option}</span><strong>{t(option.nameKey)}</strong></div><p>{t(option.descriptionKey)}</p></div><div className="pos-theme-mini"><div className="pos-theme-mini-bar"></div>{[0,1,2].map(index=><div className="pos-theme-mini-row" key={index}><span className="pos-theme-mini-icon"></span><span className="pos-theme-mini-line"></span><span className="pos-theme-mini-dot"></span></div>)}</div></label>)}
 </div><p className="pos-theme-picker-note">{t("pos_settings.theme.note")}</p></section>
 <section><div className="section-heading"><div><h2>ภาษีมูลค่าเพิ่ม / ใบกำกับภาษีอย่างย่อ</h2><p>ใช้เป็นฐานคำนวณ VAT หลังหักส่วนลดและแต้ม</p></div></div><div className="settings-grid"><label>สถานะ VAT<select value={form.vatRegistered} onChange={e=>change("vatRegistered",e.target.value)}><option value="no">ยังไม่จด VAT</option><option value="yes">จด VAT แล้ว</option></select></label><label>อัตรา VAT (%)<input type="number" min="0" max="100" step=".01" value={form.vatRate} onChange={e=>change("vatRate",e.target.value)}/></label><label>ค่าเริ่มต้นตอนขาย<select value={form.defaultVatMode} onChange={e=>change("defaultVatMode",e.target.value)}><option value="include">include VAT</option><option value="exclude">exclude VAT</option></select></label><label>สาขา<select value={form.taxBranchType} onChange={e=>change("taxBranchType",e.target.value)}><option value="headOffice">สำนักงานใหญ่</option><option value="branch">สาขา</option></select></label><label>เลขที่สาขา<input value={form.taxBranchCode} onChange={e=>change("taxBranchCode",e.target.value)}/></label><label className="full">ชื่อที่ใช้บนใบกำกับภาษี<input value={form.taxInvoiceName} onChange={e=>change("taxInvoiceName",e.target.value)}/></label><label className="full">ที่อยู่สำหรับใบกำกับภาษี<textarea rows="3" value={form.taxInvoiceAddress} onChange={e=>change("taxInvoiceAddress",e.target.value)}/></label></div></section>
 <section><div className="section-heading"><div><h2>PromptPay / โอนเงิน</h2><p>ใช้สร้าง QR ตอนรับชำระเงินและจอลูกค้า</p></div></div><div className="settings-grid"><label>เปิดใช้ QR PromptPay<select value={form.promptPayEnabled} onChange={e=>change("promptPayEnabled",e.target.value)}><option value="no">ปิด</option><option value="yes">เปิด</option></select></label><label>เบอร์ PromptPay / เลขนิติบุคคล<input value={form.promptPayId} onChange={e=>change("promptPayId",e.target.value)}/></label><label className="full">ชื่อบัญชี<input value={form.promptPayAccountName} onChange={e=>change("promptPayAccountName",e.target.value)}/></label></div></section>
 <section><div className="section-heading"><div><h2>รูปแบบการพิมพ์ใบเสร็จ</h2><p>เลือกขนาดกระดาษและการพิมพ์หลังขาย</p></div></div><div className="settings-grid"><label>ขนาดใบเสร็จ<select value={form.receiptPaperSize} onChange={e=>change("receiptPaperSize",e.target.value)}><option value="58">58mm</option><option value="80">80mm</option><option value="a4">A4</option></select></label><label>หลังบันทึกการขาย<select value={form.receiptPrintMode} onChange={e=>change("receiptPrintMode",e.target.value)}><option value="none">ไม่พิมพ์ใบเสร็จ</option><option value="auto">พิมพ์ทันที</option></select></label><label className="full">ข้อความขอบคุณ<input value={form.receiptThanks} onChange={e=>change("receiptThanks",e.target.value)}/></label><label className="full">ข้อความท้ายใบเสร็จ<textarea rows="3" value={form.receiptFooter} onChange={e=>change("receiptFooter",e.target.value)}/></label></div></section>
 <section><div className="section-heading"><div><h2>ระบบสมาชิกและแต้ม</h2><p>กำหนดการสะสมและมูลค่าแต้ม</p></div></div><div className="settings-grid"><label>เปิดระบบแต้ม<select value={form.loyaltyEnabled} onChange={e=>change("loyaltyEnabled",e.target.value)}><option value="yes">เปิด</option><option value="no">ปิด</option></select></label><label>ยอดซื้อ / 1 แต้ม<input type="number" min=".01" step=".01" value={form.spendPerPoint} onChange={e=>change("spendPerPoint",e.target.value)}/></label><label>มูลค่า 1 แต้ม<input type="number" min=".01" step=".01" value={form.pointValue} onChange={e=>change("pointValue",e.target.value)}/></label></div></section>
 <section><div className="section-heading"><div><h2>ตัวอย่างข้อมูลบนใบเสร็จ</h2><p>ตรวจสอบข้อมูลก่อนบันทึก</p></div></div><div className="receipt-preview"><strong>{form.taxInvoiceName||form.shopName||"POS ร้านค้าปลีก"}</strong><span>{form.taxInvoiceAddress||form.shopAddress}</span><span>{form.shopPhone}</span><span>{form.taxId}</span><small>VAT {form.vatRegistered==="yes"?form.vatRate+"%":"ยังไม่จด"}</small><small>ขนาด: {form.receiptPaperSize}</small><hr/><span>{form.receiptThanks}</span><small>{form.receiptFooter}</small></div></section><p className="error-text">{error}</p><div className="settings-actions"><button type="button" className="btn btn-secondary" onClick={()=>{setForm(defaults);applyPosTheme(DEFAULT_POS_THEME,tenant?.id,{cache:false})}}>คืนค่าเริ่มต้น</button><button type="submit" className="btn btn-pay" disabled={busy}>บันทึกการตั้งค่า</button></div></form></main><AppDeveloperPanel/></>;
}
