import { useEffect, useMemo, useState } from "react";
import { Navigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthProvider";
import { useTenant } from "@/tenant/TenantProvider";
import { useI18n } from "@/i18n/I18nProvider";
import { useParityPage } from "@/hooks/useParityPage";
import { closePosShift, listPosSales, listPosShifts, openPosShift } from "@/data/retailPosData";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";
import { PosNavigation } from "@/components/PosNavigation";
import { AppDeveloperPanel } from "@/components/AppDeveloperPanel";
const asDate=v=>v?.toDate?.()||new Date(v||0);
export function PosShiftsPage(){
 const authState=useAuth(),tenantState=useTenant(),{profile,user}=authState,{tenant}=tenantState,{formatNumber}=useI18n();
 const stylesReady=useParityPage({title:"กะพนักงาน",bodyClass:"pos-shifts-page",disabledGlobalStyles:["app.css","icons.css","shared-responsive.css"],styles:["retail-pos-font-local.css","pos-locale-switcher-placement.css","retail-pos.css","retail-shifts.css","retail-pos-navigation.css"]});
 const [shifts,setShifts]=useState([]),[sales,setSales]=useState([]),[ready,setReady]=useState(false),[openingCash,setOpeningCash]=useState("0"),[terminalCode,setTerminalCode]=useState("POS-01"),[cashierName,setCashierName]=useState(""),[openNote,setOpenNote]=useState(""),[closingCash,setClosingCash]=useState(""),[closeNote,setCloseNote]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const money=v=>formatNumber(Number(v||0),{minimumFractionDigits:2,maximumFractionDigits:2});
 const refresh=async()=>{if(!tenant?.id)return;setReady(false);try{const [h,s]=await Promise.all([listPosShifts(tenant.id),listPosSales(tenant.id)]);setShifts(h);setSales(s);if(!cashierName)setCashierName(profile?.displayName||profile?.name||user?.email||"")}finally{setReady(true)}};
 useEffect(()=>{refresh()},[tenant?.id]);
 const active=useMemo(()=>shifts.find(s=>s.status==="open"&&(!user?.uid||s.cashierId===user.uid))||shifts.find(s=>s.status==="open")||null,[shifts,user?.uid]);
 const shiftSales=useMemo(()=>active?sales.filter(s=>String(s.shiftId||"")===String(active.id)):[],[sales,active?.id]);
 const totals=useMemo(()=>shiftSales.reduce((a,s)=>{const v=Math.max(0,Number(s.totalAmount??s.total??0)-Number(s.refundTotal||0));a.totalSales+=v;a.billCount++;if((s.paymentMethod||s.payment?.method)==="cash")a.totalCashSales+=v;else a.totalNonCashSales+=v;return a},{totalSales:0,totalCashSales:0,totalNonCashSales:0,billCount:0}),[shiftSales]);
 const expected=Number(active?.openingCash||0)+totals.totalCashSales,diff=Number(closingCash||0)-expected;
 const open=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError("");try{await openPosShift({tenantId:tenant.id,openingCash:Number(openingCash||0),terminalCode,cashierName,note:openNote});await refresh()}catch(err){console.error(err);setError(String(err?.message||"เปิดกะไม่สำเร็จ"))}finally{setBusy(false)}};
 const close=async e=>{e.preventDefault();if(!active||busy)return;setBusy(true);setError("");try{await closePosShift({tenantId:tenant.id,shiftId:active.id,closingCash:Number(closingCash||0),totals,note:closeNote});setClosingCash("");setCloseNote("");await refresh()}catch(err){console.error(err);setError(String(err?.message||"ปิดกะไม่สำเร็จ"))}finally{setBusy(false)}};
 if(authState.status==="loading"||tenantState.status==="loading"||!stylesReady||(tenant?.id&&!ready))return null;if(!profile)return <Navigate to="/login?next=%2Freact%2Fpos%2Fshifts" replace/>;if(!tenant)return <Navigate to="/" replace/>;
 return <><header className="pos-header" data-pos-management-header><div className="app-title"><div><strong>กะพนักงาน</strong><small>เปิด–ปิดกะและสรุปเงินสดประจำกะ</small></div></div><div className="header-actions"><LocaleSwitcher/><PosNavigation profile={profile} currentKey="pos.shifts"/></div></header>
 <main data-pos-management className="shift-container">{!active?<section className="panel shift-card"><div className="shift-heading"><div><h1>เปิดกะพนักงาน</h1><p>ระบุเงินสดตั้งต้นก่อนเริ่มขาย</p></div><span className="status-badge closed">ปิดกะ</span></div><form className="shift-form" onSubmit={open}><label>พนักงาน<input required maxLength="100" value={cashierName} onChange={e=>setCashierName(e.target.value)} placeholder="ชื่อพนักงาน"/></label><label>เครื่องขาย<input required maxLength="50" value={terminalCode} onChange={e=>setTerminalCode(e.target.value)}/></label><label>เงินสดตั้งต้น<input required type="number" min="0" step="0.01" value={openingCash} onChange={e=>setOpeningCash(e.target.value)}/></label><label className="full">หมายเหตุ<input maxLength="200" value={openNote} onChange={e=>setOpenNote(e.target.value)} placeholder="ไม่บังคับ"/></label><p className="error-text full">{error}</p><button className="btn btn-pay full" disabled={busy} type="submit">เปิดกะ</button></form></section>:<section className="panel shift-card"><div className="shift-heading"><div><h1>กะที่กำลังเปิด</h1><p>{active.shiftNumber||active.id} • {active.cashierName} • {asDate(active.openedAt).toLocaleString("th-TH")}</p></div><span className="status-badge open">เปิดอยู่</span></div><section className="shift-stats">{[["เงินสดตั้งต้น",money(active.openingCash)],["ยอดขาย",money(totals.totalSales)],["ยอดเงินสด",money(totals.totalCashSales)],["ยอดโอน",money(totals.totalNonCashSales)],["จำนวนบิล",formatNumber(totals.billCount)],["เงินสดที่ควรมี",money(expected)]].map(([l,v])=><article key={l}><span>{l}</span><strong>{v}</strong></article>)}</section><form className="close-shift-form" onSubmit={close}><label>เงินสดที่นับจริง<input required type="number" min="0" step="0.01" value={closingCash} onChange={e=>setClosingCash(e.target.value)}/></label><label>หมายเหตุ<input maxLength="200" value={closeNote} onChange={e=>setCloseNote(e.target.value)} placeholder="ไม่บังคับ"/></label><div className="difference-box"><span>ผลต่าง</span><strong>{money(diff)}</strong></div><p className="error-text">{error}</p><button className="btn btn-danger" disabled={busy} type="submit">ปิดกะ</button></form></section>}
 <section className="panel history-card"><div className="history-head"><div><h2>ประวัติกะ</h2><p>กะล่าสุดจากฐานข้อมูล</p></div></div><div className="table-wrap"><table className="shift-table"><thead><tr><th>พนักงาน</th><th>เปิดกะ</th><th>ปิดกะ</th><th className="number">ยอดขาย</th><th className="number">เงินสดจริง</th><th className="number">ผลต่าง</th></tr></thead><tbody>{shifts.filter(s=>s.status==="closed").map(s=><tr key={s.id}><td>{s.cashierName||"-"}</td><td>{asDate(s.openedAt).toLocaleString("th-TH")}</td><td>{s.closedAt?asDate(s.closedAt).toLocaleString("th-TH"):"-"}</td><td className="number">{money(s.totalSales)}</td><td className="number">{money(s.closingCash)}</td><td className="number">{money(s.cashDifference)}</td></tr>)}</tbody></table></div>{!shifts.some(s=>s.status==="closed")?<div className="empty-state">ยังไม่มีประวัติกะ</div>:null}</section></main><AppDeveloperPanel/></>;
}
