import { useEffect, useMemo, useRef, useState } from "react";
import { Navigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthProvider";
import { useTenant } from "@/tenant/TenantProvider";
import { useI18n } from "@/i18n/I18nProvider";
import { useParityPage } from "@/hooks/useParityPage";
import { deletePosSupplier, listPosPurchases, listPosSuppliers, savePosSupplier } from "@/data/retailPurchasingData";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";
import { PosNavigation } from "@/components/PosNavigation";
import { AppDeveloperPanel } from "@/components/AppDeveloperPanel";
const empty={id:"",name:"",contact:"",phone:"",email:"",taxId:"",creditDays:0,address:"",note:"",active:true};
export function PosSuppliersPage(){
 const authState=useAuth(),tenantState=useTenant(),{profile}=authState,{tenant}=tenantState,{formatNumber}=useI18n(),dialogRef=useRef(null);
 const stylesReady=useParityPage({title:"ผู้จำหน่าย",bodyClass:"pos-suppliers-page",disabledGlobalStyles:["app.css","icons.css","shared-responsive.css"],styles:["retail-pos-font-local.css","pos-locale-switcher-placement.css","retail-pos.css","retail-suppliers.css","retail-pos-navigation.css"]});
 const [suppliers,setSuppliers]=useState([]),[purchases,setPurchases]=useState([]),[ready,setReady]=useState(false),[search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const money=v=>formatNumber(Number(v||0),{minimumFractionDigits:2,maximumFractionDigits:2});
 const refresh=async()=>{if(!tenant?.id)return;setReady(false);try{const [s,p]=await Promise.all([listPosSuppliers(tenant.id),listPosPurchases(tenant.id)]);setSuppliers(s);setPurchases(p)}finally{setReady(true)}};
 useEffect(()=>{refresh()},[tenant?.id]);
 const summaries=useMemo(()=>purchases.reduce((m,p)=>{const key=p.supplierId||p.supplierName,row=m.get(key)||{count:0,total:0};row.count++;row.total+=Number(p.total||0);m.set(key,row);return m},new Map()),[purchases]);
 const rows=useMemo(()=>suppliers.filter(s=>{const q=search.toLowerCase().trim(),match=!q||[s.name,s.contact,s.phone,s.email,s.taxId].join(" ").toLowerCase().includes(q);return match&&(filter==="all"||(filter==="active"?s.active!==false:s.active===false))}),[suppliers,search,filter]);
 const stats={total:suppliers.length,active:suppliers.filter(s=>s.active!==false).length,purchaseTotal:purchases.reduce((a,p)=>a+Number(p.total||0),0),purchaseCount:purchases.length};
 const openAdd=()=>{setForm(empty);setError("");dialogRef.current?.showModal?.()},openEdit=s=>{setForm({...empty,...s});setError("");dialogRef.current?.showModal?.()};
 const change=(key,value)=>setForm({...form,[key]:value});
 const submit=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError("");try{await savePosSupplier(tenant.id,form,form.id);dialogRef.current?.close?.();await refresh()}catch(err){console.error(err);setError(String(err?.message||"บันทึกผู้จำหน่ายไม่สำเร็จ"))}finally{setBusy(false)}};
 const remove=async s=>{if(!confirm("ลบผู้จำหน่าย "+s.name+" ?"))return;try{await deletePosSupplier(tenant.id,s.id);await refresh()}catch(err){alert(String(err?.message||"ลบไม่สำเร็จ"))}};
 if(authState.status==="loading"||tenantState.status==="loading"||!stylesReady||(tenant?.id&&!ready))return null;if(!profile)return <Navigate to="/login?next=%2Fpos%2Fsuppliers" replace/>;if(!tenant)return <Navigate to="/" replace/>;
 return <><header className="pos-header" data-pos-management-header><div className="app-title"><div><strong>ผู้จำหน่าย</strong><small>ทะเบียนผู้จำหน่ายและเงื่อนไขเครดิต</small></div></div><div className="header-actions"><LocaleSwitcher/><PosNavigation profile={profile} currentKey="pos.suppliers"/></div></header><main data-pos-management className="supplier-container">
 <section className="supplier-stats"><article><span>ผู้จำหน่ายทั้งหมด</span><strong>{stats.total}</strong></article><article><span>ใช้งาน</span><strong>{stats.active}</strong></article><article><span>ยอดซื้อสะสม</span><strong>{money(stats.purchaseTotal)}</strong></article><article><span>จำนวนครั้งที่ซื้อ</span><strong>{stats.purchaseCount}</strong></article></section>
 <section className="panel supplier-panel"><div className="section-heading"><div><h1>ทะเบียนผู้จำหน่าย</h1><p>ใช้สำหรับรับสินค้าและคำนวณกำหนดชำระเจ้าหนี้</p></div><button className="btn btn-pay" onClick={openAdd}>เพิ่มผู้จำหน่าย</button></div><div className="supplier-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหาชื่อ ผู้ติดต่อ เบอร์โทร อีเมล หรือเลขภาษี"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">ทั้งหมด</option><option value="active">ใช้งาน</option><option value="inactive">ปิดใช้งาน</option></select></div><div className="supplier-grid">{rows.map(s=>{const summary=summaries.get(s.id)||summaries.get(s.name)||{count:0,total:0};return <article className="supplier-card" key={s.id}><div className="supplier-card-head"><div><strong>{s.name}</strong><span>{s.active!==false?"ใช้งาน":"ปิดใช้งาน"}</span></div></div><p>{[s.contact,s.phone,s.email].filter(Boolean).join(" • ")||"-"}</p><small>{s.address||""}</small><div className="supplier-card-stats"><span>เครดิต {formatNumber(s.creditDays||0)} วัน</span><strong>{money(summary.total)} บาท • {summary.count} ครั้ง</strong></div><div className="supplier-card-actions"><button className="btn btn-secondary" onClick={()=>openEdit(s)}>แก้ไข</button><button className="btn btn-danger" onClick={()=>remove(s)}>ลบ</button></div></article>})}</div>{!rows.length?<div className="empty-state">ไม่พบผู้จำหน่าย</div>:null}</section></main>
 <dialog ref={dialogRef} className="supplier-dialog"><form method="dialog" onSubmit={submit}><h2>{form.id?"แก้ไขผู้จำหน่าย":"เพิ่มผู้จำหน่าย"}</h2><div className="supplier-form-grid"><label>ชื่อ<input required maxLength="120" value={form.name} onChange={e=>change("name",e.target.value)}/></label><label>ผู้ติดต่อ<input value={form.contact} onChange={e=>change("contact",e.target.value)}/></label><label>โทรศัพท์<input value={form.phone} onChange={e=>change("phone",e.target.value)}/></label><label>อีเมล<input type="email" value={form.email} onChange={e=>change("email",e.target.value)}/></label><label>เลขผู้เสียภาษี<input value={form.taxId} onChange={e=>change("taxId",e.target.value)}/></label><label>เครดิต (วัน)<input type="number" min="0" step="1" value={form.creditDays} onChange={e=>change("creditDays",e.target.value)}/></label><label className="supplier-wide">ที่อยู่<input value={form.address} onChange={e=>change("address",e.target.value)}/></label><label className="supplier-wide">หมายเหตุ<input value={form.note} onChange={e=>change("note",e.target.value)}/></label></div><p className="error-text">{error}</p><div className="supplier-form-actions"><button type="button" className="btn btn-secondary" onClick={()=>dialogRef.current?.close?.()}>ยกเลิก</button><button type="submit" className="btn btn-pay" disabled={busy}>บันทึก</button></div><button className="close-dialog" type="button" onClick={()=>dialogRef.current?.close?.()}>×</button></form></dialog><AppDeveloperPanel/></>;
}
