import { useEffect, useMemo, useState } from "react";
import { Navigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthProvider";
import { useTenant } from "@/tenant/TenantProvider";
import { useI18n } from "@/i18n/I18nProvider";
import { useParityPage } from "@/hooks/useParityPage";
import { listRetailProducts, listRetailStockMovements } from "@/data/retailProductsData";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";
import { PosNavigation } from "@/components/PosNavigation";
import { AppDeveloperPanel } from "@/components/AppDeveloperPanel";
const asDate=v=>v?.toDate?.()||new Date(v||0);
const dateKey=v=>{const d=asDate(v);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-")};
const typeName=t=>({purchase:"รับสินค้าเข้า",sale:"ขายสินค้า",return:"คืนสินค้า",count:"ตรวจนับสต็อก",adjustment:"ปรับสต็อก"}[t]||t||"-");
export function PosStockMovementsPage(){
 const authState=useAuth(),tenantState=useTenant(),{profile}=authState,{tenant}=tenantState,{formatNumber}=useI18n();
 const stylesReady=useParityPage({title:"เคลื่อนไหวสต็อก",bodyClass:"pos-stock-movements-page",disabledGlobalStyles:["app.css","icons.css","shared-responsive.css"],styles:["retail-pos-font-local.css","pos-locale-switcher-placement.css","retail-pos.css","retail-stock-movements.css","retail-stock-movements-scroll.css","retail-pos-navigation.css"]});
 const [rows,setRows]=useState([]),[products,setProducts]=useState([]),[ready,setReady]=useState(false),[search,setSearch]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[type,setType]=useState("all"),[product,setProduct]=useState("");
 const refresh=async()=>{if(!tenant?.id)return;setReady(false);try{const [m,p]=await Promise.all([listRetailStockMovements(tenant.id),listRetailProducts(tenant.id)]);setRows(m);setProducts(p)}finally{setReady(true)}};
 useEffect(()=>{refresh()},[tenant?.id]);
 const filtered=useMemo(()=>rows.filter(r=>{const q=search.toLowerCase().trim(),pk=product.toLowerCase().trim(),key=dateKey(r.createdAtServer||r.createdAt||r.updatedAt),text=[r.productName,r.productId,r.note,r.referenceNumber].join(" ").toLowerCase();return(!q||text.includes(q))&&(!pk||[r.productName,r.productId].join(" ").toLowerCase().includes(pk))&&(!from||key>=from)&&(!to||key<=to)&&(type==="all"||r.type===type)}),[rows,search,product,from,to,type]);
 const stats=useMemo(()=>filtered.reduce((a,r)=>{a.count++;if(r.direction==="in")a.in+=Number(r.qty||0);else a.out+=Number(r.qty||0);return a},{count:0,in:0,out:0}),[filtered]);
 const today=()=>{const k=dateKey(new Date());setFrom(k);setTo(k)},month=()=>{const n=new Date(),f=new Date(n.getFullYear(),n.getMonth(),1),l=new Date(n.getFullYear(),n.getMonth()+1,0);setFrom(dateKey(f));setTo(dateKey(l))},clear=()=>{setSearch("");setProduct("");setFrom("");setTo("");setType("all")};
 const exportCsv=()=>{const data=[["วันและเวลา","สินค้า","ประเภท","หมายเหตุ","ก่อน","เปลี่ยน","หลัง"],...filtered.map(r=>[asDate(r.createdAtServer||r.createdAt).toLocaleString("th-TH"),r.productName||r.productId,typeName(r.type),r.note||"",r.before??r.stockBefore,((r.direction==="out"?-1:1)*Number(r.qty||0)),r.after??r.stockAfter])],csv=data.map(x=>x.map(v=>"\""+String(v??"").replaceAll("\"","\"\"")+"\"").join(",")).join("\n"),blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="pos-stock-movements.csv";a.click();URL.revokeObjectURL(a.href)};
 if(authState.status==="loading"||tenantState.status==="loading"||!stylesReady||(tenant?.id&&!ready))return null;if(!profile)return <Navigate to="/login?next=%2Freact%2Fpos%2Fstock-movements" replace/>;if(!tenant)return <Navigate to="/" replace/>;
 return <><header className="pos-header" data-pos-management-header><div className="app-title"><div><strong>เคลื่อนไหวสต็อก</strong><small>ตรวจสอบการรับเข้า ขาย คืน ตรวจนับ และปรับสต็อก</small></div></div><div className="header-actions"><LocaleSwitcher/><PosNavigation profile={profile} currentKey="pos.stock_movements"/></div></header>
 <main data-pos-management className="movement-container"><section className="panel movement-filter-panel"><div className="movement-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหาสินค้า หมายเหตุ หรือเลขอ้างอิง"/><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value)}><option value="all">ทุกประเภท</option><option value="purchase">รับสินค้าเข้า</option><option value="sale">ขายสินค้า</option><option value="return">คืนสินค้า</option><option value="count">ตรวจนับสต็อก</option><option value="adjustment">ปรับสต็อก</option></select><button className="btn btn-secondary" onClick={today}>วันนี้</button><button className="btn btn-secondary" onClick={month}>เดือนนี้</button><button className="btn btn-secondary" onClick={clear}>ทั้งหมด</button></div></section>
 <section className="movement-stats"><article><span>จำนวนรายการ</span><strong>{formatNumber(stats.count)}</strong></article><article><span>รับเข้า</span><strong>{formatNumber(stats.in)}</strong></article><article><span>จ่ายออก</span><strong>{formatNumber(stats.out)}</strong></article><article><span>สุทธิ</span><strong>{formatNumber(stats.in-stats.out)}</strong></article></section>
 <section className="panel movement-report-panel"><div className="movement-report-heading section-heading"><div><h1>รายงานความเคลื่อนไหว</h1><p>{from||to?"ข้อมูลตามช่วงวันที่":"ข้อมูลทั้งหมด"}</p></div><button className="btn btn-pay" onClick={exportCsv}>ส่งออก CSV</button></div><div className="movement-product-filter"><input list="movementProductOptions" value={product} onChange={e=>setProduct(e.target.value)} placeholder="ค้นหาเฉพาะสินค้า"/><datalist id="movementProductOptions">{products.map(p=><option key={p.id} value={p.name||p.id}>{p.id}</option>)}</datalist></div><div className="table-wrap"><table className="movement-table"><thead><tr><th>วันและเวลา</th><th>สินค้า</th><th>ประเภท</th><th>หมายเหตุ</th><th className="number">ก่อน</th><th className="number">เปลี่ยน</th><th className="number">หลัง</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{asDate(r.createdAtServer||r.createdAt||r.updatedAt).toLocaleString("th-TH")}</td><td><strong>{r.productName||r.productId}</strong><small>{r.productId}</small></td><td>{typeName(r.type)}</td><td>{r.note||"-"}</td><td className="number">{formatNumber(r.before??r.stockBefore??0)}</td><td className="number">{r.direction==="out"?"-":"+"}{formatNumber(r.qty||0)}</td><td className="number">{formatNumber(r.after??r.stockAfter??0)}</td></tr>)}</tbody></table></div>{!filtered.length?<div className="empty-state movement-empty">ไม่พบความเคลื่อนไหวสต็อก</div>:null}</section></main><AppDeveloperPanel/></>;
}
