import { useEffect, useMemo, useState } from "react";
import { Navigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthProvider";
import { useTenant } from "@/tenant/TenantProvider";
import { useI18n } from "@/i18n/I18nProvider";
import { useParityPage } from "@/hooks/useParityPage";
import { commitRetailStockCount, listRetailProducts, listRetailStockCounts } from "@/data/retailProductsData";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";
import { PosNavigation } from "@/components/PosNavigation";
import { AppDeveloperPanel } from "@/components/AppDeveloperPanel";
const asDate=v=>v?.toDate?.()||new Date(v||0);
export function PosStockCountsPage(){
 const authState=useAuth(),tenantState=useTenant(),{profile,user}=authState,{tenant}=tenantState,{formatNumber}=useI18n();
 const stylesReady=useParityPage({title:"ตรวจนับสต็อก",bodyClass:"pos-stock-counts-page",disabledGlobalStyles:["app.css","icons.css","shared-responsive.css"],styles:["retail-pos-font-local.css","pos-locale-switcher-placement.css","retail-pos.css","retail-stock-counts.css","retail-pos-navigation.css"]});
 const [products,setProducts]=useState([]),[history,setHistory]=useState([]),[ready,setReady]=useState(false),[actual,setActual]=useState({}),[name,setName]=useState(""),[countDate,setCountDate]=useState(new Date().toISOString().slice(0,10)),[countedBy,setCountedBy]=useState(""),[note,setNote]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[historySearch,setHistorySearch]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const refresh=async()=>{if(!tenant?.id)return;setReady(false);try{const [p,h]=await Promise.all([listRetailProducts(tenant.id),listRetailStockCounts(tenant.id)]);setProducts(p);setHistory(h);if(!countedBy)setCountedBy(profile?.displayName||profile?.name||user?.email||"")}finally{setReady(true)}};
 useEffect(()=>{refresh()},[tenant?.id]);
 const rows=useMemo(()=>products.map(p=>{const raw=actual[p.id],has=raw!==""&&raw!=null,a=has?Number(raw):null,diff=has?a-Number(p.stock||0):0;return{...p,has,actual:a,diff,variance:diff*Number(p.cost||0)}}).filter(p=>{const q=search.toLowerCase().trim(),match=!q||[p.name,p.id,p.barcode].join(" ").toLowerCase().includes(q);if(!match)return false;if(filter==="difference")return p.has&&p.diff!==0;if(filter==="uncounted")return!p.has;return true}),[products,actual,search,filter]);
 const summary=useMemo(()=>products.reduce((a,p)=>{const raw=actual[p.id];if(raw===""||raw==null)return a;const n=Number(raw),diff=n-Number(p.stock||0);a.counted++;if(diff<0)a.short+=Math.abs(diff);if(diff>0)a.over+=diff;a.value+=diff*Number(p.cost||0);return a},{counted:0,short:0,over:0,value:0}),[products,actual]);
 const fill=()=>setActual(Object.fromEntries(products.map(p=>[p.id,String(p.stock||0)]))),clearActual=()=>setActual({}),reset=()=>{setActual({});setName("");setNote("");setError("")};
 const confirm=async()=>{if(busy)return;if(!summary.counted){setError("กรุณากรอกจำนวนที่ตรวจนับอย่างน้อย 1 รายการ");return}setBusy(true);setError("");try{await commitRetailStockCount(tenant.id,{name,countDate,countedBy,note,items:products.map(p=>({productId:p.id,actual:actual[p.id]??""}))});reset();await refresh()}catch(e){console.error(e);setError(String(e?.message||"บันทึกตรวจนับไม่สำเร็จ"))}finally{setBusy(false)}};
 const filteredHistory=useMemo(()=>{const q=historySearch.toLowerCase().trim();return history.filter(h=>!q||[h.name,h.countedBy,h.note,h.countDate].join(" ").toLowerCase().includes(q))},[history,historySearch]);
 if(authState.status==="loading"||tenantState.status==="loading"||!stylesReady||(tenant?.id&&!ready))return null;if(!profile)return <Navigate to="/login?next=%2Freact%2Fpos%2Fstock-counts" replace/>;if(!tenant)return <Navigate to="/" replace/>;
 return <><header className="pos-header" data-pos-management-header><div className="app-title"><div><strong>ตรวจนับสต็อก</strong><small>เปรียบเทียบยอดระบบกับจำนวนจริงและปรับสต็อก</small></div></div><div className="header-actions"><LocaleSwitcher/><PosNavigation profile={profile} currentKey="pos.stock_counts"/></div></header>
 <main data-pos-management className="count-container"><section className="panel count-panel"><div className="count-heading section-heading"><div><h1>ตรวจนับสต็อกรอบใหม่</h1><p>กรอกจำนวนจริงเฉพาะรายการที่ตรวจนับ</p></div><div className="count-actions-top"><button className="btn btn-secondary" onClick={fill}><i className="bi bi-clipboard-check"/><span>กรอกเท่าระบบ</span></button><button className="btn btn-secondary" onClick={clearActual}>ล้างจำนวนจริง</button></div></div>
 <div className="count-meta"><label>ชื่อรอบ<input maxLength="120" value={name} onChange={e=>setName(e.target.value)} placeholder="เช่น ตรวจนับสิ้นเดือน"/></label><label>วันที่ตรวจนับ<input type="date" value={countDate} onChange={e=>setCountDate(e.target.value)}/></label><label>ผู้ตรวจนับ<input maxLength="100" value={countedBy} onChange={e=>setCountedBy(e.target.value)}/></label><label>หมายเหตุ<input maxLength="200" value={note} onChange={e=>setNote(e.target.value)}/></label></div>
 <div className="count-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหาสินค้า รหัส หรือบาร์โค้ด"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">ทั้งหมด</option><option value="difference">มีผลต่าง</option><option value="uncounted">ยังไม่ตรวจ</option></select></div><div className="table-wrap"><table className="count-table"><thead><tr><th>สินค้า</th><th className="number">ยอดระบบ</th><th className="number">จำนวนจริง</th><th className="number">ผลต่าง</th><th className="number">มูลค่าผลต่าง</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.id}</small></td><td className="number">{formatNumber(p.stock||0)}</td><td className="number"><input type="number" min="0" step="0.001" value={actual[p.id]??""} onChange={e=>setActual({...actual,[p.id]:e.target.value})}/></td><td className="number">{p.has?formatNumber(p.diff):"-"}</td><td className="number">{p.has?formatNumber(p.variance,{minimumFractionDigits:2,maximumFractionDigits:2}):"-"}</td></tr>)}</tbody></table></div>{!rows.length?<div className="empty-state">ไม่พบสินค้า</div>:null}
 <div className="count-summary"><div><span>ตรวจแล้ว</span><strong>{formatNumber(summary.counted)}</strong></div><div><span>ขาด</span><strong>{formatNumber(summary.short)}</strong></div><div><span>เกิน</span><strong>{formatNumber(summary.over)}</strong></div><div><span>มูลค่าผลต่าง</span><strong>{formatNumber(summary.value,{minimumFractionDigits:2,maximumFractionDigits:2})}</strong></div></div><p className="error-text">{error}</p><div className="count-footer-actions"><button className="btn btn-secondary" onClick={reset}>เริ่มใหม่</button><button className="btn btn-pay" disabled={busy} onClick={confirm}>ยืนยันตรวจนับ</button></div></section>
 <section className="panel count-history-panel"><div className="section-heading"><div><h2>ประวัติการตรวจนับ</h2><p>รายการตรวจนับล่าสุดจากฐานข้อมูล</p></div></div><label className="count-history-search">ค้นหา<input value={historySearch} onChange={e=>setHistorySearch(e.target.value)} placeholder="ค้นหาชื่อรอบ ผู้ตรวจ หรือหมายเหตุ"/></label><div className="count-history">{filteredHistory.map(h=><article className="count-history-item" key={h.id}><div><strong>{h.name}</strong><span>{h.countDate} • {h.countedBy||"-"}</span><small>{h.note||"-"}</small></div><div><strong>{formatNumber(h.countedItems||0)} รายการ</strong><span>ผลต่าง {formatNumber(h.varianceValue||0,{minimumFractionDigits:2,maximumFractionDigits:2})}</span></div></article>)}</div>{!filteredHistory.length?<div className="empty-state">ยังไม่มีประวัติการตรวจนับ</div>:null}</section></main><AppDeveloperPanel/></>;
}
