import { useEffect, useMemo, useRef, useState } from "react";
import { Navigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthProvider";
import { useTenant } from "@/tenant/TenantProvider";
import { useI18n } from "@/i18n/I18nProvider";
import { useParityPage } from "@/hooks/useParityPage";
import { listPosSales, loadPosReceiptSettings } from "@/data/retailPosData";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";
import { PosNavigation } from "@/components/PosNavigation";
import { AppDeveloperPanel } from "@/components/AppDeveloperPanel";

const asDate=v=>v?.toDate?.()||new Date(v||0);
const localKey=v=>{const d=asDate(v);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-")};
const payMethod=s=>s.paymentMethod||s.payment?.method||"";
const netTotal=s=>Math.max(0,Number(s.totalAmount??s.total??0)-Number(s.refundTotal||0));
const beforeVat=s=>Math.max(0,Number(s.beforeVat??s.taxableBase??s.discountedBase??0));
const saleDiscount=s=>Number(s.discount||0)+Number(s.pointDiscount||0);

export function PosSalesPage(){
  const authState=useAuth(),tenantState=useTenant(),{profile}=authState,{tenant}=tenantState,{formatNumber}=useI18n(),dialogRef=useRef(null);
  const stylesReady=useParityPage({title:"รายงานและประวัติการขาย",bodyClass:"pos-sales-page",disabledGlobalStyles:["app.css","icons.css","shared-responsive.css"],styles:["retail-pos-font-local.css","pos-locale-switcher-placement.css","retail-pos.css","retail-sales.css","retail-sales-mobile.css","retail-pos-navigation.css"]});
  const [sales,setSales]=useState([]),[settings,setSettings]=useState(null),[ready,setReady]=useState(false),[search,setSearch]=useState(""),[dateFrom,setDateFrom]=useState(""),[dateTo,setDateTo]=useState(""),[payment,setPayment]=useState("all"),[selected,setSelected]=useState(null);
  const money=v=>formatNumber(Number(v||0),{minimumFractionDigits:2,maximumFractionDigits:2});
  const refresh=async()=>{if(!tenant?.id)return;setReady(false);try{const [rows,cfg]=await Promise.all([listPosSales(tenant.id),loadPosReceiptSettings(tenant.id)]);setSales(rows);setSettings(cfg)}finally{setReady(true)}};
  useEffect(()=>{refresh()},[tenant?.id]);
  const filtered=useMemo(()=>sales.filter(s=>{const q=search.trim().toLowerCase(),key=localKey(s.createdAt),text=[s.saleNumber,s.id,...(s.items||[]).map(i=>i.name||i.productName)].join(" ").toLowerCase();return(!q||text.includes(q))&&(!dateFrom||key>=dateFrom)&&(!dateTo||key<=dateTo)&&(payment==="all"||payMethod(s)===payment)}),[sales,search,dateFrom,dateTo,payment]);
  const stats=useMemo(()=>{let total=0,before=0,vat=0,cash=0,transfer=0,discount=0,qty=0,vatBills=0,high=0;filtered.forEach(s=>{const n=netTotal(s);total+=n;before+=beforeVat(s);vat+=Number(s.vatAmount||0);discount+=saleDiscount(s);high=Math.max(high,n);if(Number(s.vatAmount||0)>0)vatBills++;if(payMethod(s)==="cash")cash+=n;else transfer+=n;const returned=(s.returns||[]).flatMap(r=>r.items||[]).reduce((a,i)=>a+Number(i.qty||0),0);qty+=Math.max(0,Number(s.totalQty||(s.items||[]).reduce((a,i)=>a+Number(i.qty||0),0))-returned)});return{count:filtered.length,total,before,vat,cash,transfer,discount,qty,vatBills,avg:filtered.length?total/filtered.length:0,high}},[filtered]);
  const ranking=useMemo(()=>{const map=new Map();filtered.forEach(s=>{const returned={};(s.returns||[]).flatMap(r=>r.items||[]).forEach(i=>returned[i.productId]=(returned[i.productId]||0)+Number(i.qty||0));(s.items||[]).forEach(i=>{const id=i.productId||i.id||i.name,qty=Math.max(0,Number(i.qty||0)-Number(returned[id]||0));if(!qty)return;const row=map.get(id)||{name:i.name||i.productName||id,qty:0,total:0};row.qty+=qty;row.total+=qty*Number(i.price||0);map.set(id,row)})});return[...map.values()].sort((a,b)=>b.qty-a.qty).slice(0,8)},[filtered]);
  const today=()=>{const k=localKey(new Date());setDateFrom(k);setDateTo(k)},month=()=>{const n=new Date(),f=new Date(n.getFullYear(),n.getMonth(),1),l=new Date(n.getFullYear(),n.getMonth()+1,0);setDateFrom(localKey(f));setDateTo(localKey(l))},clear=()=>{setSearch("");setDateFrom("");setDateTo("");setPayment("all")};
  const openSale=s=>{setSelected(s);dialogRef.current?.showModal?.()},printSale=s=>window.open("/pos/receipt?saleId="+encodeURIComponent(s.id)+"&auto=1&paper="+encodeURIComponent(settings?.paperSize||"80"),"pos_receipt_"+String(s.id).replace(/\W/g,"_"),"popup=yes,width=460,height=760,noopener,noreferrer");
  const exportCsv=()=>{const rows=[["เลขที่บิล","วันและเวลา","ชำระโดย","ยอดก่อน VAT","VAT","ส่วนลด","ยอดขายสุทธิ"],...filtered.map(s=>[s.saleNumber||s.id,asDate(s.createdAt).toLocaleString("th-TH"),payMethod(s),beforeVat(s),Number(s.vatAmount||0),saleDiscount(s),netTotal(s)])],csv=rows.map(r=>r.map(v=>"\""+String(v??"").replaceAll("\"","\"\"")+"\"").join(",")).join("\n"),blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="pos-sales.csv";a.click();URL.revokeObjectURL(a.href)};
  if(authState.status==="loading"||tenantState.status==="loading"||!stylesReady||(tenant?.id&&!ready))return null;
  if(!profile)return <Navigate to="/login?next=%2Freact%2Fpos%2Fsales" replace/>;if(!tenant)return <Navigate to="/" replace/>;
  const cashPct=stats.total?Math.round(stats.cash/stats.total*100):0,transferPct=stats.total?100-cashPct:0;
  return <><header className="pos-header no-print" data-pos-management-header><div className="app-title"><div><strong>รายงานและประวัติการขาย</strong><small>POS ร้านค้าปลีก</small></div></div><div className="header-actions"><LocaleSwitcher/><PosNavigation profile={profile} currentKey="pos.sales"/></div></header>
  <main data-pos-management className="sales-container no-print"><section className="panel report-filter-panel"><div className="sales-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหาเลขที่บิลหรือชื่อสินค้า"/><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/><input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/><select value={payment} onChange={e=>setPayment(e.target.value)}><option value="all">ทุกช่องทางชำระ</option><option value="cash">เงินสด</option><option value="promptpay">PromptPay / โอนเงิน</option></select><button className="btn btn-secondary" onClick={today}>วันนี้</button><button className="btn btn-secondary" onClick={month}>เดือนนี้</button><button className="btn btn-secondary" onClick={clear}>ทั้งหมด</button></div></section>
  <section className="sales-stats">{[["จำนวนบิล",stats.count],["ยอดขายสุทธิ",money(stats.total)],["ยอดก่อน VAT",money(stats.before)],["VAT รวม",money(stats.vat)],["บิล VAT",stats.vatBills],["ยอดเงินสดสุทธิ",money(stats.cash)],["ยอดโอน / PromptPay สุทธิ",money(stats.transfer)],["ส่วนลดรวม",money(stats.discount)],["จำนวนสินค้าที่ขายสุทธิ",formatNumber(stats.qty)],["ยอดเฉลี่ยต่อบิล",money(stats.avg)],["บิลสูงสุด",money(stats.high)]].map(([l,v])=><article className="stat-card" key={l}><span>{l}</span><strong>{v}</strong></article>)}</section>
  <section className="report-grid"><section className="panel ranking-panel"><div className="section-heading"><div><h2>สินค้าขายดี</h2><p>เรียงตามจำนวนขายสุทธิหลังหักคืนสินค้า</p></div></div><div className="ranking-list">{ranking.map((r,i)=><div className="ranking-row" key={r.name}><span>{i+1}</span><strong>{r.name}</strong><em>{formatNumber(r.qty)} ชิ้น</em></div>)}</div>{!ranking.length?<div className="empty-state">ยังไม่มีข้อมูลสินค้าในช่วงนี้</div>:null}</section><section className="panel payment-panel"><div className="section-heading"><div><h2>สัดส่วนการชำระเงิน</h2><p>สรุปยอดสุทธิตามช่องทางรับชำระเดิม</p></div></div><div className="payment-summary-list"><div><span>เงินสด</span><strong>{cashPct}%</strong></div><div className="payment-bar"><i style={{width:cashPct+"%"}}></i></div><div><span>PromptPay / โอนเงิน</span><strong>{transferPct}%</strong></div><div className="payment-bar"><i style={{width:transferPct+"%"}}></i></div></div></section></section>
  <section className="panel sales-panel"><div className="section-heading"><div><h2>รายการขาย</h2><p>{dateFrom||dateTo?"ข้อมูลตามช่วงวันที่":"ข้อมูลทั้งหมด"}</p></div><button className="btn btn-pay" onClick={exportCsv}><i className="bi bi-download"/><span>ส่งออก CSV</span></button></div><div className="table-wrap"><table className="sales-table"><thead><tr><th>เลขที่บิล</th><th>วันและเวลา</th><th className="number">จำนวนสุทธิ</th><th>ชำระโดย</th><th>VAT</th><th className="number">ยอดก่อน VAT</th><th className="number">VAT</th><th className="number">ส่วนลด</th><th className="number">ยอดขายสุทธิ</th><th></th></tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td><strong>{s.saleNumber||s.id}</strong></td><td>{asDate(s.createdAt).toLocaleString("th-TH")}</td><td className="number">{formatNumber(Number(s.totalQty||0))}</td><td>{payMethod(s)==="cash"?"เงินสด":"PromptPay / โอนเงิน"}</td><td>{Number(s.vatAmount||0)>0?"VAT":"-"}</td><td className="number">{money(beforeVat(s))}</td><td className="number">{money(s.vatAmount)}</td><td className="number">{money(saleDiscount(s))}</td><td className="number">{money(netTotal(s))}</td><td><button className="btn btn-secondary" onClick={()=>openSale(s)}>ดูบิล</button></td></tr>)}</tbody></table></div>{!filtered.length?<div className="empty-state sales-empty">ไม่พบประวัติการขาย</div>:null}</section></main>
  <dialog ref={dialogRef} className="sale-dialog"><div className="sale-dialog-content"><div className="dialog-head no-print"><h2>รายละเอียดบิล</h2><button className="icon-btn" onClick={()=>dialogRef.current?.close?.()}><i className="bi bi-x-lg"/></button></div>{selected?<section className="receipt"><div className="receipt-header"><h1>{settings?.shopName||tenant.name||"POS ร้านค้าปลีก"}</h1><p>ใบเสร็จรับเงิน</p></div><div className="receipt-meta"><div><span>เลขที่บิล</span><strong>{selected.saleNumber||selected.id}</strong></div><div><span>วันที่</span><strong>{asDate(selected.createdAt).toLocaleString("th-TH")}</strong></div><div><span>การชำระเงิน</span><strong>{payMethod(selected)==="cash"?"เงินสด":"PromptPay / โอนเงิน"}</strong></div></div><table className="receipt-table receipt-table-history"><tbody>{(selected.items||[]).map((i,x)=><tr key={i.productId||x}><td>{i.name||i.productName} x {formatNumber(i.qty)}</td><td className="number">{money(i.price)}</td><td className="number">{money(i.lineTotal??Number(i.price||0)*Number(i.qty||0))}</td></tr>)}</tbody></table><div className="receipt-summary"><div><span>รวมสินค้า</span><strong>{money(selected.subtotal)}</strong></div><div><span>ส่วนลด</span><strong>{money(saleDiscount(selected))}</strong></div><div className="receipt-grand"><span>ยอดสุทธิ</span><strong>{money(netTotal(selected))}</strong></div></div></section>:null}<div className="dialog-actions no-print"><button className="btn btn-secondary" onClick={()=>dialogRef.current?.close?.()}><i className="bi bi-x-lg"/><span>ปิด</span></button><button className="btn btn-pay" onClick={()=>selected&&printSale(selected)}><i className="bi bi-printer"/><span>พิมพ์ใบเสร็จ</span></button></div></div></dialog><AppDeveloperPanel/></>;
}
