import { useEffect, useMemo, useRef, useState } from "react";
import { Navigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthProvider";
import { useTenant } from "@/tenant/TenantProvider";
import { useParityPage } from "@/hooks/useParityPage";
import { createStaffUser, listStaffUsers, updateStaffUser } from "@/data/adminStaff";
import { loadPosRoleSettings, savePosRoleSettings } from "@/data/retailPosSystemData";
import { POS_MENU_GROUPS } from "@/components/PosNavigation";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";
import { PosNavigation } from "@/components/PosNavigation";
import { AppDeveloperPanel } from "@/components/AppDeveloperPanel";

const EMPTY={displayName:"",email:"",password:"",confirmPassword:"",role:"cashier",businessScope:"retail_pos",active:true};
export function PosUsersPage(){
 const authState=useAuth(),tenantState=useTenant(),{profile,user:authUser}=authState,{tenant}=tenantState;
 const stylesReady=useParityPage({title:"ผู้ใช้และสิทธิ์",bodyClass:"pos-users-page",disabledGlobalStyles:["app.css","icons.css","shared-responsive.css"],styles:["retail-pos-font-local.css","pos-locale-switcher-placement.css","retail-pos.css","retail-pos-navigation.css","retail-pos-users-layout.css","retail-pos-users-mobile.css"]});
 const dialogRef=useRef(null),[users,setUsers]=useState([]),[roles,setRoles]=useState([]),[selectedRole,setSelectedRole]=useState("cashier"),[ready,setReady]=useState(false),[form,setForm]=useState(EMPTY),[busy,setBusy]=useState(""),[error,setError]=useState("");
 const load=async()=>{if(!tenant?.id)return;setReady(false);try{const [u,r]=await Promise.all([listStaffUsers(),loadPosRoleSettings(tenant.id)]);setUsers(u.filter(x=>["retail_pos","both"].includes(x.businessScope)));setRoles(r);if(!r.some(x=>x.id===selectedRole))setSelectedRole(r[0]?.id||"cashier")}finally{setReady(true)}};
 useEffect(()=>{load()},[tenant?.id]);
 const role=roles.find(r=>r.id===selectedRole)||roles[0],allItems=useMemo(()=>POS_MENU_GROUPS.flatMap(g=>g.items.map(i=>({...i,group:g.label}))),[]);
 const rolePerms=new Set(role?.permissions||[]),allAllowed=rolePerms.has("*");
 const togglePermission=key=>{if(!role)return;const next=new Set(allAllowed?allItems.map(i=>i.key):role.permissions||[]);next.has(key)?next.delete(key):next.add(key);setRoles(rows=>rows.map(r=>r.id===role.id?{...r,permissions:[...next]}:r))};
 const saveRoles=async()=>{setBusy("roles");setError("");try{await savePosRoleSettings(tenant.id,roles)}catch(e){console.error(e);setError(String(e?.message||"บันทึกสิทธิ์ไม่สำเร็จ"))}finally{setBusy("")}};
 const openCreate=()=>{setForm(EMPTY);setError("");dialogRef.current?.showModal?.()};
 const create=async e=>{e.preventDefault();if(form.password.length<8){setError("รหัสผ่านอย่างน้อย 8 ตัวอักษร");return}if(form.password!==form.confirmPassword){setError("ยืนยันรหัสผ่านไม่ตรงกัน");return}setBusy("create");setError("");try{await createStaffUser(form);dialogRef.current?.close?.();await load()}catch(err){console.error(err);setError(String(err?.message||"สร้างผู้ใช้ไม่สำเร็จ"))}finally{setBusy("")}};
 const patchUser=(uid,key,value)=>setUsers(rows=>rows.map(u=>u.uid===uid?{...u,[key]:value}:u));
 const saveUser=async u=>{if(u.uid===authUser?.uid)return;setBusy(u.uid);setError("");try{await updateStaffUser(u.uid,{displayName:u.displayName,role:u.role,businessScope:u.businessScope,active:u.active});await load()}catch(e){console.error(e);setError(String(e?.message||"บันทึกผู้ใช้ไม่สำเร็จ"))}finally{setBusy("")}};
 if(authState.status==="loading"||tenantState.status==="loading"||!stylesReady||(tenant?.id&&!ready))return null;if(!profile)return <Navigate to="/login?next=%2Freact%2Fpos%2Fusers" replace/>;if(!tenant)return <Navigate to="/" replace/>;if(!["owner","super_admin"].includes(profile.role))return <Navigate to="/pos" replace/>;
 return <><header className="pos-header" data-pos-supporting-header><div className="app-title"><div><strong>ผู้ใช้และสิทธิ์</strong><small>จัดการพนักงาน POS บทบาท และสิทธิ์เมนู</small></div></div><div className="header-actions"><LocaleSwitcher/><PosNavigation profile={profile} currentKey="pos.users"/></div></header>
 <main className="users-container" data-pos-supporting="users"><section className="panel roles-panel"><div className="section-heading"><div><h1>บทบาทและสิทธิ์</h1><p>สิทธิ์จะถูกแชร์ผ่าน Firebase settings ไปยังทุกอุปกรณ์</p></div><button className="btn btn-pay" disabled={busy==="roles"} onClick={saveRoles}>บันทึกสิทธิ์</button></div><div className="roles-layout"><aside className="role-list">{roles.map(r=><button className={"permission-card"+(r.id===selectedRole?" is-selected":"")} key={r.id} onClick={()=>setSelectedRole(r.id)}><strong>{r.name}</strong><span>{r.id} • {r.permissions?.includes("*")?"ทุกสิทธิ์":(r.permissions?.length||0)+" สิทธิ์"}</span></button>)}</aside><section className="permission-editor"><label>ชื่อบทบาท<input value={role?.name||""} onChange={e=>setRoles(rows=>rows.map(r=>r.id===role.id?{...r,name:e.target.value}:r))}/></label><div className="permission-group-grid">{POS_MENU_GROUPS.map(g=><section className="permission-group-card" key={g.id}><div className="permission-group-head"><strong>{g.label}</strong></div><div className="permission-group-items">{g.items.map(i=><label className="permission-checkbox" key={i.key}><input type="checkbox" checked={allAllowed||rolePerms.has(i.key)} disabled={allAllowed} onChange={()=>togglePermission(i.key)}/><span>{i.label}</span></label>)}</div></section>)}</div></section></div></section>
 <section className="panel users-panel"><div className="section-heading"><div><h2>พนักงาน POS</h2><p>บัญชีที่มีขอบเขต Retail POS หรือทั้งสองระบบ</p></div><button className="btn btn-pay" onClick={openCreate}>เพิ่มผู้ใช้</button></div><div className="user-list">{users.map(u=><article className="permission-card" key={u.uid}><div className="user-fields"><label>ชื่อ<input value={u.displayName} onChange={e=>patchUser(u.uid,"displayName",e.target.value)}/></label><label>อีเมล<input value={u.email} readOnly/></label><label>บทบาท<select value={u.role} onChange={e=>patchUser(u.uid,"role",e.target.value)}>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>ขอบเขต<select value={u.businessScope} onChange={e=>patchUser(u.uid,"businessScope",e.target.value)}><option value="retail_pos">Retail POS</option><option value="both">ทั้งสองระบบ</option></select></label><label>สถานะ<select value={u.active?"1":"0"} onChange={e=>patchUser(u.uid,"active",e.target.value==="1")}><option value="1">ใช้งาน</option><option value="0">ระงับ</option></select></label><button className="btn btn-primary" disabled={busy===u.uid||u.uid===authUser?.uid} onClick={()=>saveUser(u)}><i className="bi bi-floppy"/><span>บันทึก</span></button></div></article>)}</div>{!users.length?<div className="empty">ยังไม่มีผู้ใช้ POS</div>:null}</section><p className="error-text">{error}</p></main>
 <dialog ref={dialogRef} data-pos-management-dialog className="user-dialog"><form className="user-form" onSubmit={create}><div className="dialog-head"><h2>เพิ่มผู้ใช้ POS</h2><button type="button" className="icon-btn" onClick={()=>dialogRef.current?.close?.()}><i className="bi bi-x-lg"/></button></div><div className="user-form-grid"><label>ชื่อ<input required value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label>อีเมล<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>รหัสผ่าน<input required type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>ยืนยันรหัสผ่าน<input required type="password" value={form.confirmPassword} onChange={e=>setForm({...form,confirmPassword:e.target.value})}/></label><label>บทบาท<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>ขอบเขต<select value={form.businessScope} onChange={e=>setForm({...form,businessScope:e.target.value})}><option value="retail_pos">Retail POS</option><option value="both">ทั้งสองระบบ</option></select></label></div><p className="error-text">{error}</p><div className="dialog-actions"><button type="button" className="btn btn-secondary" onClick={()=>dialogRef.current?.close?.()}>ยกเลิก</button><button type="submit" className="btn btn-pay" disabled={busy==="create"}>บันทึก</button></div></form></dialog><AppDeveloperPanel/></>;
}
